In [12]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from tqdm import tqdm

# Load CSV files
# comparison_df = pd.read_csv("/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/compareContribution.csv")
comparison_df = pd.read_csv('/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/sciqa-comparisonContribution-Label.csv')
hq_df = pd.read_csv("/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/sciqa-comparisonHQs.csv")

# Load Sentence-BERT model
model = SentenceTransformer('all-MiniLM-L6-v2')  # Small, fast, and good quality

print("Encoding comparision label...")
comparison_labels = [str(i) for i in comparison_df["comparisonLabel"].tolist()]
comparison_IRIs = [str(i) for i in comparison_df["comparisonIRI"].tolist()]

target_embedding = model.encode(comparison_labels, convert_to_tensor=True)

print("\nEncoding HQ questions and finding most similar comparison label...")
predicted_comparison_label = []
predicted_comparison_IRI = []
cosine_scores_list = []
correct_predictions = []

for i, hq in enumerate(hq_df["question_string"]):
    print(f"\nEncoding HQ question {i+1}/{len(hq_df)}")
    source_embedding = model.encode(hq, convert_to_tensor=True)
    # Compute cosine similarities
    cosine_scores = cosine_similarity([source_embedding.cpu().numpy()], target_embedding.cpu().numpy())[0]
    # Find index of best match
    # find the index of the top 3 highest scores
    top_3_indices = np.argsort(cosine_scores)[-3:][::-1]
    print(cosine_scores[top_3_indices])
    cosine_scores_list.append(cosine_scores[top_3_indices])
    top3_candidates = [comparison_df.iloc[idx]['comparisonLabel'] for idx in top_3_indices]
    top3_candidate_IRIs = [comparison_df.iloc[idx]['comparisonIRI'] for idx in top_3_indices]
    # find the candidate comparison 
    goldComparisonLabel = hq_df.iloc[i]['goldComparisonLabel']
    print(goldComparisonLabel)
    print(top3_candidates)
    if goldComparisonLabel in top3_candidates:
        correct_predictions.append(1)
        print("Correct prediction")
    else:
        correct_predictions.append(0)
    print(f"Top 3 candidates for HQ question '{hq}':")
    for candidate in top3_candidates:
        print(f"  Top match candidate: {candidate}")
    predicted_comparison_label.append(top3_candidates)
    predicted_comparison_IRI.append(top3_candidate_IRIs)

hq_df["predicted_comparison_label"] = predicted_comparison_label
hq_df["predicted_comparison_IRI"] = predicted_comparison_IRI
hq_df["cosine_scores"] = cosine_scores_list
hq_df["correct_predictions"] = correct_predictions
hq_df.to_csv("/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/hq_with_sciqa_compareContribution.csv", index=False)

Encoding comparision label...

Encoding HQ questions and finding most similar comparison label...

Encoding HQ question 1/60
[0.81868416 0.29212445 0.29212445]
Summarization before 2002
['Summarization before 2002', 'Semantic representations of scholarly communication', 'Semantic representations of scholarly communication']
Correct prediction
Top 3 candidates for HQ question 'What was the most common type of approach for summarization before 2002?':
  Top match candidate: Summarization before 2002
  Top match candidate: Semantic representations of scholarly communication
  Top match candidate: Semantic representations of scholarly communication

Encoding HQ question 2/60
[0.31580895 0.21628493 0.17624506]
Pulsed electric field (PEF) treatment for bioactive compounds extraction
['Pulsed electric field (PEF) treatment for bioactive compounds extraction', 'Toxins produced by phytopathogenic Pseudomonas species and pathovars', 'Examples of cyclodextrin-containing formulations for drug delivery via ocular, nasal and pulmonary routes']
Correct prediction
Top 3 candidates for HQ question 'Which vegetables are utilized for betanin extraction?':
  Top match candidate: Pulsed electric field (PEF) treatment for bioactive compounds extraction
  Top match candidate: Toxins produced by phytopathogenic Pseudomonas species and pathovars
  Top match candidate: Examples of cyclodextrin-containing formulations for drug delivery via ocular, nasal and pulmonary routes

Encoding HQ question 3/60
[0.45773014 0.45773014 0.45773014]
Comparison of Studies on Germany's Energy Supply in 2050
["Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050"]
Correct prediction
Top 3 candidates for HQ question 'What is the average energy generation of all energy sources considered?':
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050

Encoding HQ question 4/60
[0.3319203 0.3319203 0.3319203]
Semantic representations of scholarly communication
['Ontologies for describing scholarly articles', 'Ontologies for describing scholarly articles', 'Ontologies for describing scholarly articles']
Top 3 candidates for HQ question 'What is the scope of "Decentralised Authoring, Annotations and Notifications for a Read-Write Web with Dokieli"?':
  Top match candidate: Ontologies for describing scholarly articles
  Top match candidate: Ontologies for describing scholarly articles
  Top match candidate: Ontologies for describing scholarly articles

Encoding HQ question 5/60
[0.28183842 0.27690575 0.27017918]
Examples of cyclodextrin-containing formulations for drug delivery via ocular, nasal and pulmonary routes
['Examples of cyclodextrin-containing formulations for drug delivery via ocular, nasal and pulmonary routes', 'Pilot mini collection of studies on libraries as third places.', 'Trends and methodological implications of psychodrama psychotherapy research']
Correct prediction
Top 3 candidates for HQ question 'What is the most common drug in the studies?':
  Top match candidate: Examples of cyclodextrin-containing formulations for drug delivery via ocular, nasal and pulmonary routes
  Top match candidate: Pilot mini collection of studies on libraries as third places.
  Top match candidate: Trends and methodological implications of psychodrama psychotherapy research

Encoding HQ question 6/60
[0.7814981 0.5728284 0.5728284]
Comparison of scholarly knowledge graphs
['Comparison of scholarly knowledge graphs', 'Ontologies for describing scholarly articles', 'Ontologies for describing scholarly articles']
Correct prediction
Top 3 candidates for HQ question 'Which scholarly knowledge graphs support RDF?':
  Top match candidate: Comparison of scholarly knowledge graphs
  Top match candidate: Ontologies for describing scholarly articles
  Top match candidate: Ontologies for describing scholarly articles

Encoding HQ question 7/60
[0.4385382  0.29524207 0.2951927 ]
The Use of Silicon Carbide Thin Films in Different Device Types
['Pilot mini collection of studies on libraries as third places.', 'COVID-19 Reproductive Number Estimates', 'Comparison of scholarly knowledge graphs']
Top 3 candidates for HQ question 'How many studies are published after 2019?':
  Top match candidate: Pilot mini collection of studies on libraries as third places.
  Top match candidate: COVID-19 Reproductive Number Estimates
  Top match candidate: Comparison of scholarly knowledge graphs

Encoding HQ question 8/60
[0.39728868 0.36698136 0.31543192]
Invasion Biology- Enemy release hypothesis
['COVID-19 Reproductive Number Estimates', 'Genetic variability (COI variation) in studies large sampled (>1000 sequences)', 'Assessment of picophytoplankton abundance in the Indian Ocean']
Top 3 candidates for HQ question 'What is the total number of species examined in the studies?':
  Top match candidate: COVID-19 Reproductive Number Estimates
  Top match candidate: Genetic variability (COI variation) in studies large sampled (>1000 sequences)
  Top match candidate: Assessment of picophytoplankton abundance in the Indian Ocean

Encoding HQ question 9/60
[0.52239907 0.52239907 0.52239907]
Ontologies for describing scholarly articles
['Ontologies for describing scholarly articles', 'Ontologies for describing scholarly articles', 'Ontologies for describing scholarly articles']
Correct prediction
Top 3 candidates for HQ question 'What is the full name of the EXPO ontology?':
  Top match candidate: Ontologies for describing scholarly articles
  Top match candidate: Ontologies for describing scholarly articles
  Top match candidate: Ontologies for describing scholarly articles

Encoding HQ question 10/60
[0.35771644 0.32847393 0.32722178]
Assessment of picophytoplankton abundance in the Ocean
['Assessment of picophytoplankton abundance in the Ocean', 'Assessment of picophytoplankton abundance in the Indian Ocean', 'Pilot mini collection of studies on libraries as third places.']
Correct prediction
Top 3 candidates for HQ question 'Do all studies include open ocean sampling?':
  Top match candidate: Assessment of picophytoplankton abundance in the Ocean
  Top match candidate: Assessment of picophytoplankton abundance in the Indian Ocean
  Top match candidate: Pilot mini collection of studies on libraries as third places.

Encoding HQ question 11/60
[0.23909459 0.15968095 0.14071305]
Semantic representations of scholarly communication
['Invasion Biology- Enemy release hypothesis', 'Toxins produced by phytopathogenic Pseudomonas species and pathovars', 'Trends and methodological implications of psychodrama psychotherapy research']
Top 3 candidates for HQ question 'Who is responsible for acquisition in the RASH system?':
  Top match candidate: Invasion Biology- Enemy release hypothesis
  Top match candidate: Toxins produced by phytopathogenic Pseudomonas species and pathovars
  Top match candidate: Trends and methodological implications of psychodrama psychotherapy research

Encoding HQ question 12/60
[0.40153027 0.24126863 0.14489853]
Comparison of Impact of Covid-19 on mobility behaviour
['Genetic variability (COI variation) in studies large sampled (>1000 sequences)', 'COVID-19 Reproductive Number Estimates', 'Assessment of picophytoplankton abundance in the Ocean']
Top 3 candidates for HQ question 'What is the maximum sample size?':
  Top match candidate: Genetic variability (COI variation) in studies large sampled (>1000 sequences)
  Top match candidate: COVID-19 Reproductive Number Estimates
  Top match candidate: Assessment of picophytoplankton abundance in the Ocean

Encoding HQ question 13/60
[0.8105704  0.3215635  0.20456931]
Toxins produced by phytopathogenic Pseudomonas species and pathovars
['Toxins produced by phytopathogenic Pseudomonas species and pathovars', 'Anuran antimicrobial peptides activity and mechanism against different biological membranes', 'Invasion Biology- Enemy release hypothesis']
Correct prediction
Top 3 candidates for HQ question 'Which toxins do pseudomonas species produce?':
  Top match candidate: Toxins produced by phytopathogenic Pseudomonas species and pathovars
  Top match candidate: Anuran antimicrobial peptides activity and mechanism against different biological membranes
  Top match candidate: Invasion Biology- Enemy release hypothesis

Encoding HQ question 14/60
[0.7908752  0.7908752  0.73131955]
Comparison of Scenario Factsheets from the Open Energy Platform
['Comparison of Scenario Factsheets from the Open Energy Platform', 'Comparison of Scenario Factsheets from the Open Energy Platform', "Comparison of Scenario Factsheets from the Open Energy Platform; Comparison of Studies on Germany's Energy Supply in 2050"]
Correct prediction
Top 3 candidates for HQ question 'Which scenario factsheets from the Open Energy Platform are used in studies with public funding?':
  Top match candidate: Comparison of Scenario Factsheets from the Open Energy Platform
  Top match candidate: Comparison of Scenario Factsheets from the Open Energy Platform
  Top match candidate: Comparison of Scenario Factsheets from the Open Energy Platform; Comparison of Studies on Germany's Energy Supply in 2050

Encoding HQ question 15/60
[0.39255458 0.3755758  0.3755758 ]
Comparison of Studies on Germany's Energy Supply in 2050
["Comparison of Scenario Factsheets from the Open Energy Platform; Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050"]
Correct prediction
Top 3 candidates for HQ question 'What is the minimum and maximum installed capacity for each energy source considered?':
  Top match candidate: Comparison of Scenario Factsheets from the Open Energy Platform; Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050

Encoding HQ question 16/60
[0.45268923 0.45268923 0.45268923]
Comparison of Studies on Germany's Energy Supply in 2050
["Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050"]
Correct prediction
Top 3 candidates for HQ question 'What is the average installed capacity for each energy source considered in 5 year intervals?':
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050

Encoding HQ question 17/60
[0.35766107 0.26892924 0.22319897]
Sources of major ion evolution in groundwater chemistry of developing urban areas
['Sources of major ion evolution in groundwater chemistry of developing urban areas', 'Pilot mini collection of studies on libraries as third places.', 'Anuran antimicrobial peptides activity and mechanism against different biological membranes']
Correct prediction
Top 3 candidates for HQ question 'How many studies do use Chloride as major anion?':
  Top match candidate: Sources of major ion evolution in groundwater chemistry of developing urban areas
  Top match candidate: Pilot mini collection of studies on libraries as third places.
  Top match candidate: Anuran antimicrobial peptides activity and mechanism against different biological membranes

Encoding HQ question 18/60
[0.23866022 0.21120214 0.20588912]
Comparison of the frequency of obstructive sleep apnea (OSA) in patients with mucopolysaccharidosis (MPS)
['Genetic variability (COI variation) in studies large sampled (>1000 sequences)', 'QA evaluations on QALD-6', 'QA evaluations on QALD-5']
Top 3 candidates for HQ question 'What risk factors for OSA are discovered in the paper with 100% OSA frequency?':
  Top match candidate: Genetic variability (COI variation) in studies large sampled (>1000 sequences)
  Top match candidate: QA evaluations on QALD-6
  Top match candidate: QA evaluations on QALD-5

Encoding HQ question 19/60
[0.42111492 0.14653261 0.13349296]
Brief psychotherapy for depression studies
['COVID-19 Reproductive Number Estimates', 'Assessment of picophytoplankton abundance in the Ocean', 'Prevalence of epilepsy in Europe']
Top 3 candidates for HQ question 'What is the maximum female percentage?':
  Top match candidate: COVID-19 Reproductive Number Estimates
  Top match candidate: Assessment of picophytoplankton abundance in the Ocean
  Top match candidate: Prevalence of epilepsy in Europe

Encoding HQ question 20/60
[0.49717176 0.49717176 0.49717176]
Ontologies for describing scholarly articles
['Ontologies for describing scholarly articles', 'Ontologies for describing scholarly articles', 'Ontologies for describing scholarly articles']
Correct prediction
Top 3 candidates for HQ question 'Which ontology has the most classes?':
  Top match candidate: Ontologies for describing scholarly articles
  Top match candidate: Ontologies for describing scholarly articles
  Top match candidate: Ontologies for describing scholarly articles

Encoding HQ question 21/60
[0.62854093 0.24240178 0.189701  ]
Survey of most suitable computational intelligence technique for prediction of Sepsis using physiological data as features
['Survey of most suitable computational intelligence technique for prediction of Sepsis using physiological data as features', 'The effect of the COVID-19 pandemic on well-being', 'Comparison of studies related to psychotherapeutic interventions in cancer']
Correct prediction
Top 3 candidates for HQ question 'What are the objectives for Sepsis prediction?':
  Top match candidate: Survey of most suitable computational intelligence technique for prediction of Sepsis using physiological data as features
  Top match candidate: The effect of the COVID-19 pandemic on well-being
  Top match candidate: Comparison of studies related to psychotherapeutic interventions in cancer

Encoding HQ question 22/60
[0.48562497 0.48562497 0.48562497]
Comparison of Studies on Germany's Energy Supply in 2050
["Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050"]
Correct prediction
Top 3 candidates for HQ question 'What is the average energy generation for each energy source considered?':
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050

Encoding HQ question 23/60
[0.2940301  0.21983601 0.21135262]
Fullerene-based photocatalysts in organic pollutants degradation
['Genetic variability (COI variation) in studies large sampled (>1000 sequences)', 'Pilot mini collection of studies on libraries as third places.', 'Cost functions estimation for port sector']
Top 3 candidates for HQ question 'What is the average efficency for experiments?':
  Top match candidate: Genetic variability (COI variation) in studies large sampled (>1000 sequences)
  Top match candidate: Pilot mini collection of studies on libraries as third places.
  Top match candidate: Cost functions estimation for port sector

Encoding HQ question 24/60
[0.81638324 0.5061816  0.430767  ]
The effect of the COVID-19 pandemic on well-being
['The effect of the COVID-19 pandemic on well-being', 'Comparison of Impact of Covid-19 on mobility behaviour', 'COVID-19 Reproductive Number Estimates']
Correct prediction
Top 3 candidates for HQ question 'Which indicators for well-being are used in the studies on the effect of COVID-19?':
  Top match candidate: The effect of the COVID-19 pandemic on well-being
  Top match candidate: Comparison of Impact of Covid-19 on mobility behaviour
  Top match candidate: COVID-19 Reproductive Number Estimates

Encoding HQ question 25/60
[0.32938218 0.28241295 0.24178657]
Results of studies on embryonic eggshell thickness erosion in three groups of birds representing different developmental modes
['COVID-19 Reproductive Number Estimates', 'Results of studies on embryonic eggshell thickness erosion in three groups of birds representing different developmental modes', 'Genetic variability (COI variation) in studies large sampled (>1000 sequences)']
Correct prediction
Top 3 candidates for HQ question 'What is the maximum egg mass in studies?':
  Top match candidate: COVID-19 Reproductive Number Estimates
  Top match candidate: Results of studies on embryonic eggshell thickness erosion in three groups of birds representing different developmental modes
  Top match candidate: Genetic variability (COI variation) in studies large sampled (>1000 sequences)

Encoding HQ question 26/60
[0.19895628 0.18197906 0.15541115]
Transforming lignin-derived monomers to catechol, phenol, and benzene by heterogeneous catalysts
['Cost functions estimation for port sector', 'Catalysts for the Liquid-Phase Hydrogenation of Alkynes overview', 'The Use of Silicon Carbide Thin Films in Different Device Types']
Top 3 candidates for HQ question 'For what product minimum conversion was obtained?':
  Top match candidate: Cost functions estimation for port sector
  Top match candidate: Catalysts for the Liquid-Phase Hydrogenation of Alkynes overview
  Top match candidate: The Use of Silicon Carbide Thin Films in Different Device Types

Encoding HQ question 27/60
[0.65266126 0.597365   0.597365  ]
Comparison of Scenario Factsheets from the Open Energy Platform; Comparison of Studies on Germany's Energy Supply in 2050
["Comparison of Scenario Factsheets from the Open Energy Platform; Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050"]
Correct prediction
Top 3 candidates for HQ question 'In which papers are energy system scenarios used that consider the 2050 time frame?':
  Top match candidate: Comparison of Scenario Factsheets from the Open Energy Platform; Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050

Encoding HQ question 28/60
[0.23576657 0.21381585 0.21372703]
Pilot mini collection of studies on libraries as third places.
['Examples of cyclodextrin-containing formulations for drug delivery via ocular, nasal and pulmonary routes', 'QA evaluations on QALD-5', 'Trends and methodological implications of psychodrama psychotherapy research']
Top 3 candidates for HQ question 'Which methods are used?':
  Top match candidate: Examples of cyclodextrin-containing formulations for drug delivery via ocular, nasal and pulmonary routes
  Top match candidate: QA evaluations on QALD-5
  Top match candidate: Trends and methodological implications of psychodrama psychotherapy research

Encoding HQ question 29/60
[0.4236588 0.4236588 0.4236588]
Comparison of Studies on Germany's Energy Supply in 2050
["Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050", "Comparison of Studies on Germany's Energy Supply in 2050"]
Correct prediction
Top 3 candidates for HQ question 'What is the average installed capacity of all energy sources considered?':
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050

Encoding HQ question 30/60

In [26]:
from IPython.display import Markdown as md
from orkg import ORKG, Hosts
import warnings
warnings.filterwarnings('ignore')

orkg = ORKG(host=Hosts.PRODUCTION)
df = pd.read_csv("/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/hq_with_sciqa_compareContribution.csv")
df.head()

prompt_column = []
response_column = []

for i in range(len(df)):
    question_id = df.iloc[i]['question_id']
    question_string = df.iloc[i]['question_string']
    predicted_comparison_IRI = df.iloc[i]['predicted_comparison_IRI']
    goldComparionIRI = df.iloc[i]['goldComparisonIRI']
    prompts = []
    responses = []
    print(f"comparison IRIs: {predicted_comparison_IRI}")
    print(f"type of comparison IRIs: {type(predicted_comparison_IRI)}")
    # convert the string representation of list back to list
    predicted_comparison_IRI = eval(predicted_comparison_IRI)
    print(f"Converted comparison IRIs: {predicted_comparison_IRI}")
    print(f"type of converted comparison IRIs: {type(predicted_comparison_IRI)}")
    # iterate through the top 3 predicted comparison IRIs
    for i, comparison_id in enumerate(predicted_comparison_IRI):
        print(f"Generating prompt for question ID {question_id} with comparison ID {comparison_id}")
        try:
            comparison_df = orkg.contributions.compare_dataframe(comparison_id=comparison_id)
        # some IRIs may not be valid, so we need to handle the exception
        except Exception as e:
            print(f"Error occurred while fetching comparison dataframe: {e}")
            continue
        # convert the dataframe to a csv data
        csv_data = comparison_df.to_csv(index=False)
        prompt = f"""
        Given the following CSV data representing a comparison of scientific contributions, and a question.
        Analyze the data and provide insights to answer the question.
        CSV Data:
        {csv_data}
        Question: {question_string}.
        Answer:
        """
        print(prompt)
        prompts.append(prompt)
        # response = get_response_from_language_model(prompt)
        # responses.append(response)
    # store the prompts and responses in the original dataframe
    prompt_column.append(prompts)
    # response_column.append(responses)
    print(f"Processed question ID: {question_id}")
df['prompts'] = prompt_column
# df['responses'] = response_column

comparison IRIs: ['R6948', 'R8364', 'R8364']
type of comparison IRIs: <class 'str'>
Converted comparison IRIs: ['R6948', 'R8364', 'R8364']
type of converted comparison IRIs: <class 'list'>
Generating prompt for question ID HQ0013 with comparison ID R6948

        Given the following CSV data representing a comparison of scientific contributions, and a question.
        Analyze the data and provide insights to answer the question.
        CSV Data:
        Automatic Abstracting Research at Chemical Abstracts Service/<italic>Contribution 1</italic>,Automatic condensation of electronic publications by sentence selection/<italic>Contribution 1</italic>,Automated text summarization and the SUMMARIST system/<italic>Contribution 1</italic>,"Trainable, scalable summarization using robust NLP and machine learning/<italic>Contribution 1</italic>",Generating Natural Language Summaries from Multiple On-Line Sources/<italic>Contribution 1</italic>,Discourse Trees Are Good Indicators of Importance in Text/<italic>Contribution 1</italic>,Information Fusion in the Context of Multi-Document Summarization/<italic>Contribution 1</italic>,A multilingual news summarizer/<italic>Contribution 1</italic>,Experiments in Single and Multi-Document Summarization Using MEAD/<italic>Contribution 1</italic>,"NewsInEssence: A System For Domain-Independent, Real-Time News Clustering and Multi-Document Summarization/<italic>Contribution 1</italic>",WebInEssence: A Personalized Web-Based Multi-Document Summarization and Recommendation System/<italic>Contribution 1</italic>,Automated multi-document summarization in NeATS/<italic>Contribution 1</italic>,News/<italic>Contribution 1</italic>,GLEANS: A Generator of Logical Extracts and Abstracts for Nice Summaries/<italic>Contribution 1</italic>,Generating Single and Multi-Document Summaries with GISTEXTER/<italic>Contribution 1</italic>,Generating Indicative-Informative Summaries with SumUM/<italic>Contribution 1</italic>
Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization,Automatic text summarization
Single document,Multiple documents,Multiple documents,Single document,Multiple documents,Single document,Multiple documents,Multiple documents,Multiple documents,Multiple documents,Multiple documents,Multiple documents,Multiple documents,Multiple documents,Multiple documents<break/>Single document,Multiple documents
Implementation,Implementation,SUMMARIST,Implementation,SUMMONS,Implementation,Implementation,Multilingual Sunmmrization System,Implementation,NewsInEssence,WebInEssence,NeATS,Columbia's Newsblaster,GLEANS,GISTEXTER,SumUM
Algebraic,Algebraic,Algebraic,Algebraic,Algebraic,Algebraic,Algebraic,Graph based,Algebraic,Graph based,Statistical,Graph based,Graph based,Algebraic,Algebraic,Algebraic
,,Generic,Generic,,,,,,,Generic,,,,,
Abstractive,Abstractive,Extractive,Extractive,Abstractive<break/>Extractive,Extractive,Abstractive,Extractive,Extractive,Extractive,Extractive,Extractive,Extractive,Abstractive<break/>Extractive,Abstractive<break/>Extractive,Abstractive
,Relative utility<break/>F-measure<break/>Recall<break/>Precision,Relative utility<break/>F-measure<break/>Recall<break/>Precision,Relative utility<break/>F-measure<break/>Recall<break/>Precision,,Relative utility<break/>F-measure<break/>Recall<break/>Precision,Relative utility<break/>F-measure<break/>Recall<break/>Precision,Relative utility<break/>F-measure<break/>Recall<break/>Precision,,,,Relative utility<break/>F-measure<break/>Recall<break/>Precision,Relative utility<break/>F-measure<break/>Recall<break/>Precision,,Relative utility<break/>F-measure<break/>Recall<break/>Precision,Relative utility<break/>F-measure<break/>Recall<break/>Precision

        Question: What was the most common type of approach for summarization before 2002?.
        Answer:

Generating prompt for question ID HQ0013 with comparison ID R8364

        Given the following CSV data representing a comparison of scientific contributions, and a question.
        Analyze the data and provide insights to answer the question.
        CSV Data:
        Open Research Knowledge Graph: Next Generation Infrastructure for Semantic Scholarly Knowledge/<italic> ORKG System</italic>,The anatomy of a nanopublication/<italic>Contribution 1</italic>,"Micropublications: a semantic model for claims, evidence, arguments and annotations in biomedical communications/<italic>Contribution 1</italic>",Research Articles in Simplified HTML: a Web-first format for HTML-based scholarly articles/<italic>Contribution 1</italic>,"Decentralised Authoring, Annotations and Notifications for a Read-Write Web with dokieli/<italic>Contribution 1</italic>"
ORKG,Nanopublications,Micropublications,RASH,Dokie.li
Authors<break/>Crowdsourcing,Authors<break/>Automatic extraction,Authors,Authors,Authors
Prospective<break/>Retrospective,Prospective<break/>Retrospective,Prospective,Prospective,Prospective
Free text,Free text,Free text,Quoted text,Quoted text
Summary,Statement level,Full paper,Full paper,Full paper
Partially,Partially,T,N,T
T,T,N,Partially,N
T,T,T,T,T
Yes,N,T,T,T
Partially,T,T,N,N
Metadata<break/>RDF,RDF,OWL<break/>RDF,HTML<break/>RDFa,HTML<break/>RDFa

        Question: What was the most common type of approach for summarization before 2002?.
        Answer:

Generating prompt for question ID HQ0013 with comparison ID R8364

        Given the following CSV data representing a comparison of scientific contributions, and a question.
        Analyze the data and provide insights to answer the question.
        CSV Data:
        Open Research Knowledge Graph: Next Generation Infrastructure for Semantic Scholarly Knowledge/<italic> ORKG System</italic>,The anatomy of a nanopublication/<italic>Contribution 1</italic>,"Micropublications: a semantic model for claims, evidence, arguments and annotations in biomedical communications/<italic>Contribution 1</italic>",Research Articles in Simplified HTML: a Web-first format for HTML-based scholarly articles/<italic>Contribution 1</italic>,"Decentralised Authoring, Annotations and Notifications for a Read-Write Web with dokieli/<italic>Contribution 1</italic>"
ORKG,Nanopublications,Micropublications,RASH,Dokie.li
Authors<break/>Crowdsourcing,Authors<break/>Automatic extraction,Authors,Authors,Authors
Prospective<break/>Retrospective,Prospective<break/>Retrospective,Prospective,Prospective,Prospective
Free text,Free text,Free text,Quoted text,Quoted text
Summary,Statement level,Full paper,Full paper,Full paper
Partially,Partially,T,N,T
T,T,N,Partially,N
T,T,T,T,T
Yes,N,T,T,T
Partially,T,T,N,N
Metadata<break/>RDF,RDF,OWL<break/>RDF,HTML<break/>RDFa,HTML<break/>RDFa

        Question: What was the most common type of approach for summarization before 2002?.
        Answer:

Processed question ID: HQ0013
comparison IRIs: ['R75363', 'R69027', 'R155621']
type of comparison IRIs: <class 'str'>
Converted comparison IRIs: ['R75363', 'R69027', 'R155621']
type of converted comparison IRIs: <class 'list'>
Generating prompt for question ID HQ0061 with comparison ID R75363

        Given the following CSV data representing a comparison of scientific contributions, and a question.
        Analyze the data and provide insights to answer the question.
        CSV Data:
        Optimization of Pulsed Electric Field Treatment for the Extraction of Bioactive Compounds from Blackcurrant/<italic>Contribution 1</italic>,"Effects of pulsed electric field-assisted treatment on the extraction, antioxidant activity and structure of naringin/<italic>Contribution 1</italic>",The Impact of Pulsed Electric Field on the Extraction of Bioactive Compounds from Beetroot/<italic>Contribution 1</italic>,Pulsed electric fields as a green technology for the extraction of bioactive compounds from thinned peach by-products/<italic>Contribution 1</italic>
Pulsed electric field (PEF) treatment for bioactive compounds extraction,Pulsed electric field (PEF) treatment for bioactive compounds extraction,Pulsed electric field (PEF) treatment for bioactive compounds extraction,Pulsed electric field (PEF) treatment for bioactive compounds extraction
Blackcurrant,Pomelo peel,Beetroot,Thinned peach
Phenolic compounds,Naringin,Betanin,Phenolic compounds
Needles,Parallel plates,Parallel plates,Parallel plates
650,2000,4380,3000
1950,10000,6250,5000
50,10,10,10
500,50,30,50
100,,0.1,0.003
15,40,,35
1318,4000,4380,5000
20,,4.10,5.98
45,70,,
19,20,329,

        Question: Which vegetables are utilized for betanin extraction?.
        Answer:

Generating prompt for question ID HQ0061 with comparison ID R69027

        Given the following CSV data representing a comparison of scientific contributions, and a question.
        Analyze the data and provide insights to answer the question.
        CSV Data:
        Pseudomonas/<italic>Pseudomonas syringae pathovar atropurpurea</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar coronafaciens</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar garcae</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar glycinea</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar lachrymans</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar maculicola</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar morsprunorum</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar phaseolicola</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar savastanoi</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar syringae</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar tabaci</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar tagetis</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar tomato</italic>,Pseudomonas/<italic>Pseudomonas syringae pathovar tolaasii</italic>
bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins,bacterial toxins
Coronatine,Tabtoxinine beta-lactam,Tabtoxinine beta-lactam,Coronatine<break/>Polysaccharide,Polysaccharide,Coronatine,Coronatine,Phaseolotoxin,Cytokinin<break/>indole acetate,Syringomycin<break/>Syringopeptin<break/>Syringotoxin,Tabtoxinine beta-lactam,Tagetitoxin,Coronatine,Tolaasin
,Glutamine synthetase,Glutamine synthetase,,,,,Ornithine transcarbamylase,,Plasma membrane,Glutamine synthetase,Chloroplastic RNA polymerase,,Plasma membrane

        Question: Which vegetables are utilized for betanin extraction?.
        Answer:

Generating prompt for question ID HQ0061 with comparison ID R155621

        Given the following CSV data representing a comparison of scientific contributions, and a question.
        Analyze the data and provide insights to answer the question.
        CSV Data:
        Cyclodextrins in acetazolamide eye drop formulations/<italic>Contribution 1</italic>,Topically effective ocular hypotensive acetazolamide and ethoxyzolamide formulations in rabbits/<italic>Contribution 1</italic>,Development of a cyclodextrin-based aqueous cyclosporin A eye drop formulations/<italic>Contribution 1</italic>,"Cyclodextrins in eye drop formulations: enhanced topical delivery of corticosteroids to the eye: Acta
 Ophthalmologica
 Scandinavica
 2002/<italic>Contribution 1</italic>",Topical and systemic absorption in delivery of dexamethasone to the anterior and posterior segments of the eye/<italic>Contribution 1</italic>,Comparison of topical 0.7% dexamethasone–cyclodextrin with 0.1% dexamethasone sodium phosphate for postcataract inflammation/<italic>Contribution 1</italic>,Topical drug delivery to the posterior segment of the eye: anatomical and physiological considerations/<italic>Contribution 1</italic>,Cyclodextrin solubilization of carbonic anhydrase inhibitor drugs: Formulation of dorzolamide eye drop microparticle suspension/<italic>Contribution 1</italic>,Considerations in the use of hydroxypropyl-Î²-cyclodextrin in the formulation of aqueous ophthalmic solutions of hydrocortisone/<italic>Contribution 1</italic>,"Current Ocular Drug Delivery Challenges for N-acetylcarnosine: Novel Patented Routes and Modes of Delivery, Design for Enhancement of Therapeutic Activity and Drug Delivery Relationships/<italic>Contribution 1</italic>",Influence of Hydroxypropyl β-Cyclodextrin on the Corneal Permeation of Pilocarpine/<italic>Contribution 1</italic>,The effects of water-soluble cyclodextrins on the histological integrity of the rat nasal mucosa/<italic>Contribution 1</italic>,"Improvement of Nasal Bioavailability of Luteinizing Hormone-Releasing Hormone Agonist, Buserelin, by Cyclodextrin Derivatives in Rats/<italic>Contribution 1</italic>",Hypocalcemic effect of salmon calcitonin following single and repeated nasal and intravenous administration in young rabbits/<italic>Contribution 1</italic>,Solid microparticles based on chitosan or methyl-β-cyclodextrin: A first formulative approach to increase the nose-to-brain transport of deferoxamine mesylate/<italic>Contribution 1</italic>,Physico-chemical characterization of disoxaril–dimethyl-β-cyclodextrin inclusion complex and in vitro permeation studies/<italic>Contribution 1</italic>,Nasal Absorption Enhancement of 17β-Estradiol by Dimethyl-β-Cyclodextrin in Rabbits and Rats/<italic>Contribution 1</italic>,Absorption Enhancing Effect of Cyclodextrins on Intranasally Administered Insulin in Rats/<italic>Contribution 1</italic>,Nasal Insulin Delivery with Dimethyl-β-Cyclodextrin as an Absorption Enhancer in Rabbits: Powder More Effective than Liquid Formulations/<italic>Contribution 1</italic>,Cyclodextrin solubilization of benzodiazepines: formulation of midazolam nasal spray/<italic>Contribution 1</italic>,Preparation of prostaglandin E1-hydroxypropyl-β-cyclodextrin complex and its nasal delivery in rats/<italic>Contribution 1</italic>,Interest of cyclodextrins in spray-dried microparticles formulation for sustained pulmonary delivery of budesonide/<italic>Contribution 1</italic>,A cyclosporin A/maltosyl- -cyclodextrin complex for inhalation therapy of asthma/<italic>Contribution 1</italic>,"The Effect of Cyclodextrins on the In Vitro and In Vivo Properties of Insulin-Loaded Poly (D,L-Lactic-Co-Glycolic Acid) Microspheres: EFFECT OF CYCLODEXTRINS ON MICROSPHERES/<italic>Contribution 1</italic>",Encapsulation of insulin–cyclodextrin complex in PLGA microspheres: a new approach for prolonged pulmonary insulin delivery/<italic>Contribution 1</italic>,Pulmonary Absorption of Insulin Mediated by Tetradecyl-β-Maltoside and Dimethyl-β-Cyclodextrin/<italic>Contribution 1</italic>,Effect of dimethyl‐β‐cyclodextrin concentrations on the pulmonary delivery of recombinant human growth hormone dry powder in rats/<italic>Contribution 1</italic>,Formulation of rifampicin–cyclodextrin complexes for lung nebulization/<italic>Contribution 1</italic>,Pulmonary Delivery of Salmon Calcitonin Dry Powders Containing Absorption Enhancers in Rats/<italic>Contribution 1</italic>,Inhaled Voriconazole for Prevention of Invasive Pulmonary Aspergillosis/<italic>Contribution 1</italic>
Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Ocular drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Nasal drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty,Pulmonary drug delivery<break/>Cyclodextrin complexes to enhance drug solubilty or bioavailabilty
Trimethyl-beta-cyclodextrin (TM-β-CD)<break/>Dimethyl-beta-cyclodextrin (DM-β-CD)<break/>Beta-cyclodextrin (βCD),2-hydroxypropyl-β-cyclodextrin (HP-β-CD),ɣ-Cyclodextrin (ɣ-CD)<break/>⍺-Cyclodextrin (⍺-CD),2-hydroxypropyl-β-cyclodextrin (HP-β-CD),Randomly methylated-β-Cyclodextrin (RMβCD),2-hydroxypropyl-β-cyclodextrin (HP-β-CD),Randomly methylated-β-Cyclodextrin (RMβCD),ɣ-Cyclodextrin (ɣ-CD),2-hydroxypropyl-β-cyclodextrin (HP-β-CD),⍺-Cyclodextrin (⍺-CD),2-hydroxypropyl-β-cyclodextrin (HP-β-CD),Randomly methylated-β-Cyclodextrin (RMβCD)<break/>2-hydroxypropyl-β-cyclodextrin (HP-β-CD)<break/>Beta-cyclodextrin (βCD),Dimethyl-beta-cyclodextrin (DM-β-CD),Trimethyl-beta-cyclodextrin (TM-β-CD)<break/>Randomly methylated-β-Cyclodextrin (RMβCD)<break/>Dimethyl-beta-cyclodextrin (DM-β-CD),Randomly methylated-β-Cyclodextrin (RMβCD),Dimethyl-beta-cyclodextrin (DM-β-CD),Dimethyl-beta-cyclodextrin (DM-β-CD),Dimethyl-beta-cyclodextrin (DM-β-CD)<break/>2-hydroxypropyl-β-cyclodextrin (HP-β-CD)<break/>ɣ-Cyclodextrin (ɣ-CD)<break/>Beta-cyclodextrin (βCD)<break/>⍺-Cyclodextrin (⍺-CD),Dimethyl-beta-cyclodextrin (DM-β-CD),Sulfobutylether-β-cyclodextrin (SBEβCD),2-hydroxypropyl-β-cyclodextrin (HP-β-CD),2-hydroxypropyl-β-cyclodextrin (HP-β-CD),Maltosyl-αCD,Dimethyl-beta-cyclodextrin (DM-β-CD),Dimethyl-beta-cyclodextrin (DM-β-CD),Dimethyl-beta-cyclodextrin (DM-β-CD),Dimethyl-beta-cyclodextrin (DM-β-CD),Randomly methylated-β-Cyclodextrin (RMβCD)<break/>2-hydroxypropyl-β-cyclodextrin (HP-β-CD),Dimethyl-beta-cyclodextrin (DM-β-CD),Sulfobutylether-β-cyclodextrin (SBEβCD)

In [27]:
df.head()

,question_id,question_string,sparql_query,goldComparisonIRI,goldComparisonLabel,predicted_comparison_label,predicted_comparison_IRI,cosine_scores,correct_predictions,prompts
0,HQ0013,What was the most common type of approach for ...,SELECT ?approach ?approach_label\nWHERE {\n o...,R6948,Summarization before 2002,"['Summarization before 2002', 'Semantic repres...","['R6948', 'R8364', 'R8364']",[0.81868416 0.29212445 0.29212445],1,[\n Given the following CSV data repres...
1,HQ0061,Which vegetables are utilized for betanin extr...,"SELECT ?vegetables, ?vegetables_labels\nWHERE ...",R75363,Pulsed electric field (PEF) treatment for bioa...,['Pulsed electric field (PEF) treatment for bi...,"['R75363', 'R69027', 'R155621']",[0.31580895 0.21628493 0.17624506],1,[\n Given the following CSV data repres...
2,HQ0049,What is the average energy generation of all e...,SELECT (AVG(?elec_gen_value) AS ?average_elec_...,R153801,Comparison of Studies on Germany's Energy Supp...,"[""Comparison of Studies on Germany's Energy Su...","['R153801', 'R153801', 'R153801']",[0.45773014 0.45773014 0.45773014],1,[]
3,HQ0002,"What is the scope of ""Decentralised Authoring,...",SELECT ?scope \nWHERE {\n orkgr:R8364 orkgp:c...,R8364,Semantic representations of scholarly communic...,['Ontologies for describing scholarly articles...,"['R8342', 'R8342', 'R8342']",[0.3319203 0.3319203 0.3319203],0,[\n Given the following CSV data repres...
4,HQ0072,What is the most common drug in the studies?,"SELECT ?drug, ?drug_labels\nWHERE {\n orkgr:R...",R155621,Examples of cyclodextrin-containing formulatio...,['Examples of cyclodextrin-containing formulat...,"['R155621', 'R110361', 'R44980']",[0.28183842 0.27690575 0.27017918],1,[\n Given the following CSV data repres...

## Show the comparison Table

In [10]:
from IPython.display import Markdown as md
from orkg import ORKG, Hosts
import warnings
warnings.filterwarnings('ignore')

# comparison_id = input("Please enter the ID of the comparison you want to analyze: ")
comparison_id = "R6187"

orkg = ORKG(host=Hosts.PRODUCTION)
df = orkg.contributions.compare_dataframe(comparison_id=comparison_id)
# convert the dataframe to a csv data
csv_data = df.to_csv(index=False)
prompt = f"""
Given the following CSV data representing a comparison of scientific contributions, and a question.
Analyze the data and provide insights to answer the question.
CSV Data:
{csv_data}
Question: Provide a summary of the key differences and similarities among the contributions in the comparison.
Answer:
"""

print(prompt)
resource = orkg.resources.by_id(id=comparison_id)
md("## Title: {} ([View](https://orkg.org/comparison/{}))".format(resource.content["label"],comparison_id))

Given the following CSV data representing a comparison of scientific contributions, and a question.
Analyze the data and provide insights to answer the question.
CSV Data:
Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic>,A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic>,A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic>,Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic>,Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic>,Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic>,Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic>,A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic>,Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic>
Community detection algorithm<break/>Logistic regression,Heuristic-based<break/>Unsupervised and Adaptive,Community detection algorithm<break/>Support Vector Machine,First gradient boosted tree applied on similar authors and then agglomerative clustering is performed,Web and authorship correlations,Self-citation clustering rules with other rules,"First pure clusters of data are found and model is trained, tested on them",Similar authors share co-authors and have high topic similarity,Web page genre identification based graph re-clustering
Tani Moto coefficient,Levenshtein,Cosine<break/>Levenshtein distance<break/>TF-IDF<break/>Tanimoto,Cosine<break/>Jaro–Winkler<break/>TF-IDF,Cosine<break/>Modified sigmoid function<break/>Name popularity measure,Cosine<break/>TF-IDF,Cosine<break/>Euclidean,Cosine<break/>TF-IDF<break/>Tanimoto,Multi-dimensional scaling
T,F,T,F,F,F,F,F,Robust
Self-designed WoS,DBLP,Microsoft Academic Service,INSPIRE,DBLP,WoK Thomson Reuters,BDBComp<break/>DBLP<break/>SyGAR,Microsoft Academic Service,DBLP
F-measure<break/>Precision<break/>Recall,F1<break/>Precision<break/>Recall,F1<break/>Precision<break/>Recall,F1<break/>Pairwise Precision<break/>Recall,F1<break/>Pairwise Precision<break/>Recall,F1<break/>Pairwise Precision<break/>Recall,K metric<break/>Pairwise F1,F1,F1
Homonyms problem,Homonyms problem<break/>Synonyms problem,Homonyms problem<break/>Synonyms problem,Homonyms problem<break/>Synonyms problem,Homonyms problem<break/>Synonyms problem,Homonyms problem<break/>Synonyms problem,Homonyms problem<break/>Synonyms problem,Homonyms problem<break/>Synonyms problem,Homonyms problem<break/>Synonyms problem
Abstract<break/>Average author contribution<break/>Citations<break/>Difference in years of publication<break/>Keywords<break/>Title words,Affiliation<break/>Authors<break/>Home page<break/>Title words<break/>Venues,Affiliation<break/>Keywords<break/>Publication year<break/>Title words<break/>Venues,Abstract<break/>Affiliation<break/>Authors<break/>Collaborations<break/>Keywords<break/>References<break/>Subject<break/>Title words<break/>Venues<break/>Year difference,Authors<break/>Title words<break/>Venues,Addresses<break/>Affiliation<break/>Authors<break/>Citations languages<break/>Combinations of these<break/>Subject categories<break/>Title words<break/>Venues<break/>Year,Authors<break/>Title words<break/>Venues,Affiliation<break/>Keywords<break/>Title words<break/>Venues,Explicit web genre
Requires too many parameters,It involves user on multiple stages,Complex rules and topic modeling needed,Not applicable to all DL’s data set,Inherently slow as using web info,Too much processing for large set of features,Threshold selection is a big issue,Fails in case of sole authors,Slow as using web information

Question: Provide a summary of the key differences and similarities among the contributions in the comparison.
Answer:

## Title: Semi-supervised author name disambiguation ([View](https://orkg.org/comparison/R6187))

In [28]:
from IPython.display import Markdown as md
from orkg import ORKG, Hosts
import warnings
warnings.filterwarnings('ignore')

# comparison_id = input("Please enter the ID of the comparison you want to analyze: ")
comparison_id = "R6187"
orkg = ORKG(host=Hosts.PRODUCTION)
df = orkg.contributions.compare_dataframe(comparison_id=comparison_id)

In [29]:
df.head()

,Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic>,A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic>,A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic>,Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic>,Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic>,Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic>,Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic>,A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic>,Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic>
Method,Community detection algorithm<break/>Logistic ...,Heuristic-based<break/>Unsupervised and Adaptive,Community detection algorithm<break/>Support V...,First gradient boosted tree applied on similar...,Web and authorship correlations,Self-citation clustering rules with other rules,First pure clusters of data are found and mode...,Similar authors share co-authors and have high...,Web page genre identification based graph re-c...
uses similarity,Tani Moto coefficient,Levenshtein,Cosine<break/>Levenshtein distance<break/>TF-I...,Cosine<break/>Jaro–Winkler<break/>TF-IDF,Cosine<break/>Modified sigmoid function<break/...,Cosine<break/>TF-IDF,Cosine<break/>Euclidean,Cosine<break/>TF-IDF<break/>Tanimoto,Multi-dimensional scaling
Uncertainty,T,F,T,F,F,F,F,F,Robust
dataset,Self-designed WoS,DBLP,Microsoft Academic Service,INSPIRE,DBLP,WoK Thomson Reuters,BDBComp<break/>DBLP<break/>SyGAR,Microsoft Academic Service,DBLP
Performance metric,F-measure<break/>Precision<break/>Recall,F1<break/>Precision<break/>Recall,F1<break/>Precision<break/>Recall,F1<break/>Pairwise Precision<break/>Recall,F1<break/>Pairwise Precision<break/>Recall,F1<break/>Pairwise Precision<break/>Recall,K metric<break/>Pairwise F1,F1,F1

In [4]:
row_labels = df.index.tolist()
column_labels = df.columns.tolist()
print(row_labels)
print(column_labels)
for row in df.index:
    for col in df.columns:
        print(row, col, df.loc[row, col])

['Method', 'uses similarity', 'Uncertainty', 'dataset', 'Performance metric', 'deals with', 'Evidence', 'Limitations']
['Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic>', 'A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic>', 'A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic>', 'Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic>', 'Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic>', 'Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic>', 'Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic>', 'A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic>', 'Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic>']
Method Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic> Community detection algorithm<break/>Logistic regression
Method A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic> Heuristic-based<break/>Unsupervised and Adaptive
Method A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic> Community detection algorithm<break/>Support Vector Machine
Method Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic> First gradient boosted tree applied on similar authors and then agglomerative clustering is performed
Method Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic> Web and authorship correlations
Method Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic> Self-citation clustering rules with other rules
Method Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic> First pure clusters of data are found and model is trained, tested on them
Method A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic> Similar authors share co-authors and have high topic similarity
Method Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic> Web page genre identification based graph re-clustering
uses similarity Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic> Tani Moto coefficient
uses similarity A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic> Levenshtein
uses similarity A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic> Cosine<break/>Levenshtein distance<break/>TF-IDF<break/>Tanimoto
uses similarity Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic> Cosine<break/>Jaro–Winkler<break/>TF-IDF
uses similarity Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic> Cosine<break/>Modified sigmoid function<break/>Name popularity measure
uses similarity Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic> Cosine<break/>TF-IDF
uses similarity Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic> Cosine<break/>Euclidean
uses similarity A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic> Cosine<break/>TF-IDF<break/>Tanimoto
uses similarity Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic> Multi-dimensional scaling
Uncertainty Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic> T
Uncertainty A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic> F
Uncertainty A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic> T
Uncertainty Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic> F
Uncertainty Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic> F
Uncertainty Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic> F
Uncertainty Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic> F
Uncertainty A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic> F
Uncertainty Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic> Robust
dataset Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic> Self-designed WoS
dataset A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic> DBLP
dataset A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic> Microsoft Academic Service
dataset Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic> INSPIRE
dataset Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic> DBLP
dataset Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic> WoK Thomson Reuters
dataset Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic> BDBComp<break/>DBLP<break/>SyGAR
dataset A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic> Microsoft Academic Service
dataset Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic> DBLP
Performance metric Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic> F-measure<break/>Precision<break/>Recall
Performance metric A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic> F1<break/>Precision<break/>Recall
Performance metric A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic> F1<break/>Precision<break/>Recall
Performance metric Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic> F1<break/>Pairwise Precision<break/>Recall
Performance metric Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic> F1<break/>Pairwise Precision<break/>Recall
Performance metric Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic> F1<break/>Pairwise Precision<break/>Recall
Performance metric Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic> K metric<break/>Pairwise F1
Performance metric A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic> F1
Performance metric Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic> F1
deals with Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic> Homonyms problem
deals with A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic> Homonyms problem<break/>Synonyms problem
deals with A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic> Homonyms problem<break/>Synonyms problem
deals with Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic> Homonyms problem<break/>Synonyms problem
deals with Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic> Homonyms problem<break/>Synonyms problem
deals with Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic> Homonyms problem<break/>Synonyms problem
deals with Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic> Homonyms problem<break/>Synonyms problem
deals with A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic> Homonyms problem<break/>Synonyms problem
deals with Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic> Homonyms problem<break/>Synonyms problem
Evidence Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic> Abstract<break/>Average author contribution<break/>Citations<break/>Difference in years of publication<break/>Keywords<break/>Title words
Evidence A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic> Affiliation<break/>Authors<break/>Home page<break/>Title words<break/>Venues
Evidence A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic> Affiliation<break/>Keywords<break/>Publication year<break/>Title words<break/>Venues
Evidence Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic> Abstract<break/>Affiliation<break/>Authors<break/>Collaborations<break/>Keywords<break/>References<break/>Subject<break/>Title words<break/>Venues<break/>Year difference
Evidence Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic> Authors<break/>Title words<break/>Venues
Evidence Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic> Addresses<break/>Affiliation<break/>Authors<break/>Citations languages<break/>Combinations of these<break/>Subject categories<break/>Title words<break/>Venues<break/>Year
Evidence Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic> Authors<break/>Title words<break/>Venues
Evidence A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic> Affiliation<break/>Keywords<break/>Title words<break/>Venues
Evidence Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic> Explicit web genre
Limitations Author disambiguation using multi-aspect similarity indicators/<italic>Contribution 1</italic> Requires too many parameters
Limitations A Real-time Heuristic-based Unsupervised Method for Name Disambiguation in Digital Libraries/<italic>Contribution 1</italic> It involves user on multiple stages
Limitations A semi-supervised approach for author disambiguation in KDD CUP 2013/<italic>Contribution 1</italic> Complex rules and topic modeling needed
Limitations Ethnicity Sensitive Author Disambiguation Using Semi-supervised Learning/<italic>Contribution 1</italic> Not applicable to all DL’s data set
Limitations Disambiguating authors in citations on the web and authorship correlations/<italic>Contribution 1</italic> Inherently slow as using web info
Limitations Citation-based bootstrapping for large-scale author disambiguation/<italic>Contribution 1</italic> Too much processing for large set of features
Limitations Self-training author name disambiguation for information scarce scenarios/<italic>Contribution 1</italic> Threshold selection is a big issue
Limitations A Unified Semi-supervised Framework for Author Disambiguation in Academic Social Network/<italic>Contribution 1</italic> Fails in case of sole authors
Limitations Robust hybrid name disambiguation framework for large databases/<italic>Contribution 1</italic> Slow as using web information

## Enbedding questions and candidate entities from the KG

In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from tqdm import tqdm
import os

# comparison_df = pd.read_csv("/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/compareContribution.csv")
entity_df = pd.read_csv('/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/orkg_entity_labels.csv')
hq_df = pd.read_csv("/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/sciqa-comparisonHQs.csv")
candidates = entity_df["label"].tolist()
# Load Sentence-BERT model
model = SentenceTransformer('all-MiniLM-L6-v2')  # Small, fast, and good quality

print("Encoding entity label...")
entity_labels = [str(i) for i in entity_df["label"].tolist()]

embeddings_path = "entity_embeddings.npy"
if os.path.exists(embeddings_path):
    print(f"Loading embeddings from cache: {embeddings_path}")
    target_embeddings = np.load(embeddings_path)
    # ensure shape matches
    if target_embeddings.shape[0] != len(candidates):
        print("Warning: cached embeddings length differs from candidates; recomputing.")
else:
    target_embeddings = model.encode(entity_labels, convert_to_tensor=True)
    np.save(embeddings_path, target_embeddings.cpu().numpy())


print("\nEncoding HQ questions and finding most similar entity label...")
results = []
cosine_scores_list = []
correct_predictions = []

for i, hq in enumerate(hq_df["question_string"]):
    print(f"\nEncoding HQ question {i+1}/{len(hq_df)}")
    source_embedding = model.encode(hq, convert_to_tensor=True)
    # Compute cosine similarities
    cosine_scores = cosine_similarity([source_embedding.cpu().numpy()], target_embedding.cpu().numpy())[0]
    # Find index of best match
    # find the index of the top 3 highest scores
    top_3_indices = np.argsort(cosine_scores)[-3:][::-1]
    print(cosine_scores[top_3_indices])
    cosine_scores_list.append(cosine_scores[top_3_indices])
    top3_candidates = [entity_df.iloc[idx]['label'] for idx in top_3_indices]
    goldComparisonLabel = hq_df.iloc[i]['goldComparisonLabel']
    print(goldComparisonLabel)
    print(top3_candidates)
    if goldComparisonLabel in top3_candidates:
        correct_predictions.append(1)
        print("Correct prediction")
    else:
        correct_predictions.append(0)
    print(f"Top 3 candidates for HQ question '{hq}':")
    for candidate in top3_candidates:
        print(f"  Top match candidate: {candidate}")
    results.append(top3_candidates)

hq_df["predicted_entity_label"] = results
hq_df["cosine_scores"] = cosine_scores_list
hq_df["correct_predictions"] = correct_predictions
hq_df.to_csv("/Users/sherrypan/GitHub/GAR_SKGQA/datasets/sciqa/project_data/hq_with_candidate_entity_labels.csv", index=False)

/Users/sherrypan/miniconda3/envs/graphrag/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Encoding entity label...

Encoding HQ questions and finding most similar entity label...

Encoding HQ question 1/60
[0.8186841  0.75431174 0.7377292 ]
Summarization before 2002
['Summarization before 2002', 'Summarization techniques', 'Recent summarization efforts']
Correct prediction
Top 3 candidates for HQ question 'What was the most common type of approach for summarization before 2002?':
  Top match candidate: Summarization before 2002
  Top match candidate: Summarization techniques
  Top match candidate: Recent summarization efforts

Encoding HQ question 2/60
[0.59633607 0.52660865 0.52005404]
Pulsed electric field (PEF) treatment for bioactive compounds extraction
['Betanin', 'Nutrient extraction', 'Vegetables and their products']
Top 3 candidates for HQ question 'Which vegetables are utilized for betanin extraction?':
  Top match candidate: Betanin
  Top match candidate: Nutrient extraction
  Top match candidate: Vegetables and their products

Encoding HQ question 3/60
[0.7272678 0.6179595 0.6179595]
Comparison of Studies on Germany's Energy Supply in 2050
['Reported Energy Generation [TWh] of Compared Studies for All Sources', 'Reported Energy Generation [TWh] of Compared Studies', 'Reported Energy Generation [TWh] of Compared Studies']
Top 3 candidates for HQ question 'What is the average energy generation of all energy sources considered?':
  Top match candidate: Reported Energy Generation [TWh] of Compared Studies for All Sources
  Top match candidate: Reported Energy Generation [TWh] of Compared Studies
  Top match candidate: Reported Energy Generation [TWh] of Compared Studies

Encoding HQ question 4/60
[0.9214269  0.9214268  0.47891486]
Semantic representations of scholarly communication
['Decentralised Authoring, Annotations and Notifications for a Read-Write Web with dokieli', 'Decentralised Authoring, Annotations and Notifications for a Read-Write Web with dokieli', 'The Publishing Workflow Ontology (PWO)']
Top 3 candidates for HQ question 'What is the scope of "Decentralised Authoring, Annotations and Notifications for a Read-Write Web with Dokieli"?':
  Top match candidate: Decentralised Authoring, Annotations and Notifications for a Read-Write Web with dokieli
  Top match candidate: Decentralised Authoring, Annotations and Notifications for a Read-Write Web with dokieli
  Top match candidate: The Publishing Workflow Ontology (PWO)

Encoding HQ question 5/60
[0.63069445 0.62583566 0.62392783]
Examples of cyclodextrin-containing formulations for drug delivery via ocular, nasal and pulmonary routes
['Drug Discovery', 'Experimental drug', 'Pharmacologic Substance']
Top 3 candidates for HQ question 'What is the most common drug in the studies?':
  Top match candidate: Drug Discovery
  Top match candidate: Experimental drug
  Top match candidate: Pharmacologic Substance

Encoding HQ question 6/60
[0.8062691 0.8062691 0.8062691]
Comparison of scholarly knowledge graphs
['Scholarly Knowledge Graphs', 'Scholarly Knowledge Graphs', 'Scholarly Knowledge Graphs']
Top 3 candidates for HQ question 'Which scholarly knowledge graphs support RDF?':
  Top match candidate: Scholarly Knowledge Graphs
  Top match candidate: Scholarly Knowledge Graphs
  Top match candidate: Scholarly Knowledge Graphs

Encoding HQ question 7/60
[0.6469984  0.61406547 0.60820144]
The Use of Silicon Carbide Thin Films in Different Device Types
['18 retrieved studies', 'Number of studied papers', 'number of publications']
Top 3 candidates for HQ question 'How many studies are published after 2019?':
  Top match candidate: 18 retrieved studies
  Top match candidate: Number of studied papers
  Top match candidate: number of publications

Encoding HQ question 8/60
[0.6879203  0.6581263  0.64100033]
Invasion Biology- Enemy release hypothesis
['Potential number of undescribed species', 'Change in number of native species', 'Percentage change in number of native species']
Top 3 candidates for HQ question 'What is the total number of species examined in the studies?':
  Top match candidate: Potential number of undescribed species
  Top match candidate: Change in number of native species
  Top match candidate: Percentage change in number of native species

Encoding HQ question 9/60
[0.6320975 0.6320975 0.6320975]
Ontologies for describing scholarly articles
['ontology', 'ontology', 'Ontology']
Top 3 candidates for HQ question 'What is the full name of the EXPO ontology?':
  Top match candidate: ontology
  Top match candidate: ontology
  Top match candidate: Ontology

Encoding HQ question 10/60
[0.56505543 0.5402488  0.5363519 ]
Assessment of picophytoplankton abundance in the Ocean
['Oceanography', 'Progress in Oceanography', 'Deep Sea Research Part A. Oceanographic Research Papers']
Top 3 candidates for HQ question 'Do all studies include open ocean sampling?':
  Top match candidate: Oceanography
  Top match candidate: Progress in Oceanography
  Top match candidate: Deep Sea Research Part A. Oceanographic Research Papers

Encoding HQ question 11/60
[0.5621729  0.4436192  0.43384713]
Semantic representations of scholarly communication
['RASH', 'purpuric skin rash', 'Immune System']
Top 3 candidates for HQ question 'Who is responsible for acquisition in the RASH system?':
  Top match candidate: RASH
  Top match candidate: purpuric skin rash
  Top match candidate: Immune System

Encoding HQ question 12/60
[0.8216983 0.7259623 0.7259623]
Comparison of Impact of Covid-19 on mobility behaviour
['Sample Size', 'amount of samples', 'amount of samples']
Top 3 candidates for HQ question 'What is the maximum sample size?':
  Top match candidate: Sample Size
  Top match candidate: amount of samples
  Top match candidate: amount of samples

Encoding HQ question 13/60
[0.81057036 0.7640568  0.7462542 ]
Toxins produced by phytopathogenic Pseudomonas species and pathovars
['Toxins produced by phytopathogenic Pseudomonas species and pathovars', 'Pseudomonas', 'Microbial toxins']
Correct prediction
Top 3 candidates for HQ question 'Which toxins do pseudomonas species produce?':
  Top match candidate: Toxins produced by phytopathogenic Pseudomonas species and pathovars
  Top match candidate: Pseudomonas
  Top match candidate: Microbial toxins

Encoding HQ question 14/60
[0.7908752 0.7908752 0.7908752]
Comparison of Scenario Factsheets from the Open Energy Platform
['Comparison of Scenario Factsheets from the Open Energy Platform', 'Comparison of Scenario Factsheets from the Open Energy Platform', 'Comparison of Scenario Factsheets from the Open Energy Platform']
Correct prediction
Top 3 candidates for HQ question 'Which scenario factsheets from the Open Energy Platform are used in studies with public funding?':
  Top match candidate: Comparison of Scenario Factsheets from the Open Energy Platform
  Top match candidate: Comparison of Scenario Factsheets from the Open Energy Platform
  Top match candidate: Comparison of Scenario Factsheets from the Open Energy Platform

Encoding HQ question 15/60
[0.603535   0.59700817 0.5842142 ]
Comparison of Studies on Germany's Energy Supply in 2050
['Energy requirement', 'Reported Installed Capacity [GW] of Compared Studies for All Sources', 'Reported Installed Capacity [GW] of Compared Studies for Photovoltaics']
Top 3 candidates for HQ question 'What is the minimum and maximum installed capacity for each energy source considered?':
  Top match candidate: Energy requirement
  Top match candidate: Reported Installed Capacity [GW] of Compared Studies for All Sources
  Top match candidate: Reported Installed Capacity [GW] of Compared Studies for Photovoltaics

Encoding HQ question 16/60
[0.5882959  0.56512463 0.5514559 ]
Comparison of Studies on Germany's Energy Supply in 2050
['Reported Installed Capacity [GW] of Compared Studies for All Sources', 'Specific energy consumption', 'Total energy supply']
Top 3 candidates for HQ question 'What is the average installed capacity for each energy source considered in 5 year intervals?':
  Top match candidate: Reported Installed Capacity [GW] of Compared Studies for All Sources
  Top match candidate: Specific energy consumption
  Top match candidate: Total energy supply

Encoding HQ question 17/60
[0.61924785 0.6192478  0.51147354]
Sources of major ion evolution in groundwater chemistry of developing urban areas
['chloride', 'Chloride', 'sodium chloride equivalent']
Top 3 candidates for HQ question 'How many studies do use Chloride as major anion?':
  Top match candidate: chloride
  Top match candidate: Chloride
  Top match candidate: sodium chloride equivalent

Encoding HQ question 18/60
[0.48979124 0.38557133 0.38254172]
Comparison of the frequency of obstructive sleep apnea (OSA) in patients with mucopolysaccharidosis (MPS)
['risk factors', 'Measuring the supply chain risk and vulnerability in frequency space', 'Apple Mobility Trend Report']
Top 3 candidates for HQ question 'What risk factors for OSA are discovered in the paper with 100% OSA frequency?':
  Top match candidate: risk factors
  Top match candidate: Measuring the supply chain risk and vulnerability in frequency space
  Top match candidate: Apple Mobility Trend Report

Encoding HQ question 19/60
[0.67540276 0.53549397 0.53549397]
Brief psychotherapy for depression studies
['31% women', 'percentage', 'Percentage']
Top 3 candidates for HQ question 'What is the maximum female percentage?':
  Top match candidate: 31% women
  Top match candidate: percentage
  Top match candidate: Percentage

Encoding HQ question 20/60
[0.74280065 0.69615006 0.69615006]
Ontologies for describing scholarly articles
['Performance of ontology classes at each level', 'ontology', 'ontology']
Top 3 candidates for HQ question 'Which ontology has the most classes?':
  Top match candidate: Performance of ontology classes at each level
  Top match candidate: ontology
  Top match candidate: ontology

Encoding HQ question 21/60
[0.7942403  0.7018404  0.69435906]
Survey of most suitable computational intelligence technique for prediction of Sepsis using physiological data as features
['Performance Sepsis prediction', 'Predictive models for severe sepsis in adult ICU patients', 'From vital signs to clinical outcomes for patients with sepsis: a machine learning basis for a clinical decision support system']
Top 3 candidates for HQ question 'What are the objectives for Sepsis prediction?':
  Top match candidate: Performance Sepsis prediction
  Top match candidate: Predictive models for severe sepsis in adult ICU patients
  Top match candidate: From vital signs to clinical outcomes for patients with sepsis: a machine learning basis for a clinical decision support system

Encoding HQ question 22/60
[0.7115474  0.63849634 0.63849634]
Comparison of Studies on Germany's Energy Supply in 2050
['Reported Energy Generation [TWh] of Compared Studies for All Sources', 'Reported Energy Generation [TWh] of Compared Studies', 'Reported Energy Generation [TWh] of Compared Studies']
Top 3 candidates for HQ question 'What is the average energy generation for each energy source considered?':
  Top match candidate: Reported Energy Generation [TWh] of Compared Studies for All Sources
  Top match candidate: Reported Energy Generation [TWh] of Compared Studies
  Top match candidate: Reported Energy Generation [TWh] of Compared Studies

Encoding HQ question 23/60
[0.5705138 0.5705138 0.5705138]
Fullerene-based photocatalysts in organic pollutants degradation
['Experiments', 'Experiments', 'Experiments']
Top 3 candidates for HQ question 'What is the average efficency for experiments?':
  Top match candidate: Experiments
  Top match candidate: Experiments
  Top match candidate: Experiments

Encoding HQ question 24/60
[0.81638324 0.81638324 0.81638324]
The effect of the COVID-19 pandemic on well-being
['The effect of the COVID-19 pandemic on well-being', 'The effect of the COVID-19 pandemic on well-being', 'The effect of the COVID-19 pandemic on well-being']
Correct prediction
Top 3 candidates for HQ question 'Which indicators for well-being are used in the studies on the effect of COVID-19?':
  Top match candidate: The effect of the COVID-19 pandemic on well-being
  Top match candidate: The effect of the COVID-19 pandemic on well-being
  Top match candidate: The effect of the COVID-19 pandemic on well-being

Encoding HQ question 25/60
[0.5208477  0.5126683  0.49043065]
Results of studies on embryonic eggshell thickness erosion in three groups of birds representing different developmental modes
['Eggs and their products', 'Eggs', 'Mass ratio']
Top 3 candidates for HQ question 'What is the maximum egg mass in studies?':
  Top match candidate: Eggs and their products
  Top match candidate: Eggs
  Top match candidate: Mass ratio

Encoding HQ question 26/60
[0.57525456 0.5517833  0.5119497 ]
Transforming lignin-derived monomers to catechol, phenol, and benzene by heterogeneous catalysts
['Conversions', 'Conversion', 'Minimum']
Top 3 candidates for HQ question 'For what product minimum conversion was obtained?':
  Top match candidate: Conversions
  Top match candidate: Conversion
  Top match candidate: Minimum

Encoding HQ question 27/60
[0.6065245 0.597365  0.5893792]
Comparison of Scenario Factsheets from the Open Energy Platform; Comparison of Studies on Germany's Energy Supply in 2050
['Energy scenarios for germany', "Comparison of Studies on Germany's Energy Supply in 2050", 'Helmholtz Energy System 2050 Initiative']
Top 3 candidates for HQ question 'In which papers are energy system scenarios used that consider the 2050 time frame?':
  Top match candidate: Energy scenarios for germany
  Top match candidate: Comparison of Studies on Germany's Energy Supply in 2050
  Top match candidate: Helmholtz Energy System 2050 Initiative

Encoding HQ question 28/60
[0.8454462  0.82450485 0.82450485]
Pilot mini collection of studies on libraries as third places.
['Methods-Techniques', 'Methods', 'Methods']
Top 3 candidates for HQ question 'Which methods are used?':
  Top match candidate: Methods-Techniques
  Top match candidate: Methods
  Top match candidate: Methods

Encoding HQ question 29/60
[0.6622808  0.6033709  0.59927326]
Comparison of Studies on Germany's Energy Supply in 2050
['Reported Installed Capacity [GW] of Compared Studies for All Sources', 'Reported Installed Capacity [GW] of Compared Studies for Photovoltaics', 'Total energy supply']
Top 3 candidates for HQ question 'What is the average installed capacity of all energy sources considered?':
  Top match candidate: Reported Installed Capacity [GW] of Compared Studies for All Sources
  Top match candidate: Reported Installed Capacity [GW] of Compared Studies for Photovoltaics
  Top match candidate: Total energy supply

Encoding HQ question 30/60
[0.6265935 0.6265935 0.6265934]
Catalysts for the Liquid-Phase Hydrogenation of Alkynes overview
['Substrate', 'substrate', 'Substrate']
Top 3 candidates for HQ question 'What is the most common substrate for catalysts?':
  Top match candidate: Substrate
  Top match candidate: substrate
  Top match candidate: Substrate

Encoding HQ question 31/60
[0.6872029 0.6872029 0.6872029]
COVID-19 Reproductive Number Estimates
['Reproductive number estimates 2019-nCoV', 'Reproductive number estimates 2019-nCoV', 'Reproductive number estimates 2019-nCoV']
Top 3 candidates for HQ question 'What is the average reproductive number for studies?':
  Top match candidate: Reproductive number estimates 2019-nCoV
  Top match candidate: Reproductive number estimates 2019-nCoV
  Top match candidate: Reproductive number estimates 2019-nCoV

Encoding HQ question 32/60
[0.71077037 0.6571787  0.6571787 ]
Mineralogical analysis of Mars in Visible-infrared wavelength range of electromagnetic spectrum using MRO's CRISM-3
['Study Subject', 'Study', 'study']
Top 3 candidates for HQ question 'What are areas of study?':
  Top match candidate: Study Subject
  Top match candidate: Study
  Top match candidate: study

Encoding HQ question 33/60
[0.6573016  0.63636136 0.5905705 ]
Comparison of Studies on Germany's Energy Supply in 2050
['Energy requirement', 'Reported Energy Generation [TWh] of Compared Studies for All Sources', 'Specific energy consumption']
Top 3 candidates for HQ question 'What is the minimum and maximum energy generation for each energy source considered?':
  Top match candidate: Energy requirement
  Top match candidate: Reported Energy Generation [TWh] of Compared Studies for All Sources
  Top match candidate: Specific energy consumption

Encoding HQ question 34/60
[0.79653674 0.79653674 0.79653674]
A review of Airborne visible/infrared imaging spectrometer- Next Generation (AVIRIS-NG) hyperspectral images for the identification and characterization of minerals
['preprocessing', 'preprocessing', 'preprocessing']
Top 3 candidates for HQ question 'What preprocessing methods are used?':
  Top match candidate: preprocessing
  Top match candidate: preprocessing
  Top match candidate: preprocessing

Encoding HQ question 35/60
[0.588429   0.5690372  0.56739324]
Trends and methodological implications of psychodrama psychotherapy research
['research activity', 'Laboratory location of research study', 'Researchers']
Top 3 candidates for HQ question 'In what country was conducted research with the largest number of participants?':
  Top match candidate: research activity
  Top match candidate: Laboratory location of research study
  Top match candidate: Researchers

Encoding HQ question 36/60
[0.8842397  0.66792715 0.6648447 ]
Graph-based author name disambiguation
['Evaluating the Use of Social Networks in Author Name Disambiguation in Digital Libraries', 'Graph-based author name disambiguation', 'Network based Framework for Author Name Disambiguation Applications']
Correct prediction
Top 3 candidates for HQ question 'what are the evidence and limitations of paper "Evaluating the Use of Social Networks in Author Name Disambiguation in Digital Libraries"?':
  Top match candidate: Evaluating the Use of Social Networks in Author Name Disambiguation in Digital Libraries
  Top match candidate: Graph-based author name disambiguation
  Top match candidate: Network based Framework for Author Name Disambiguation Applications

Encoding HQ question 37/60
[0.7117483  0.69325006 0.69325006]
Ontologies for describing scholarly articles
['Ontology URI', 'The Document Components Ontology (DoCO)', 'The Document Components Ontology (DoCO)']
Top 3 candidates for HQ question 'What is the base URL of "The Document Components Ontology"?':
  Top match candidate: Ontology URI
  Top match candidate: The Document Components Ontology (DoCO)
  Top match candidate: The Document Components Ontology (DoCO)

Encoding HQ question 38/60
[0.6710266  0.6501527  0.64618146]
QA evaluations on QALD-6
['Recall and Precision', 'precision, recall, accuracy', 'Precision and recall']
Top 3 candidates for HQ question 'What is the precision and recall of SemGraphQA?':
  Top match candidate: Recall and Precision
  Top match candidate: precision, recall, accuracy
  Top match candidate: Precision and recall

Encoding HQ question 39/60
[0.7943982  0.71856713 0.65215236]
Prevalence of chromosome 1 abnor- malities in hematologic malignancies
['Number of patients', 'Total patient population', '366 Patients']
Top 3 candidates for HQ question 'What is the total number of patients in the studies?':
  Top match candidate: Number of patients
  Top match candidate: Total patient population
  Top match candidate: 366 Patients

Encoding HQ question 40/60
[0.7077956 0.7077956 0.7077956]
Semantic representations of scholarly communication
['Knowledge Representation', 'Knowledge Representation', 'Knowledge Representation']
Top 3 candidates for HQ question 'What is the most common Knowledge representation method?':
  Top match candidate: Knowledge Representation
  Top match candidate: Knowledge Representation
  Top match candidate: Knowledge Representation

Encoding HQ question 41/60
[0.592865 0.592865 0.592865]

In [1]:
from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS, OWL

# Define the ontology schema content
ontology_schema = """
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix bf: <http://id.loc.gov/ontologies/bibframe/> .
@prefix bibo: <http://purl.org/ontology/bibo/> .
@prefix bibtex: <http://purl.org/net/nknouf/ns/bibtex#> .
@prefix cito: <http://purl.org/spar/cito/> .
@prefix datacite: <http://purl.org/spar/datacite/> .
@prefix dbo: <http://dbpedia.org/ontology/> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix litre: <http://purl.org/spar/literal/> .
@prefix locid: <http://id.loc.gov/vocabulary/identifiers/> .
@prefix locrel: <http://id.loc.gov/vocabulary/relators/> .
@prefix schema: <https://schema.org/> .
@prefix wd: <http://www.wikidata.org/entity/> .
@prefix wdt: <http://www.wikidata.org/prop/direct/> .
@prefix dblp: <https://dblp.org/rdf/schema#> .

<https://dblp.org/rdf/schema>
    dct:abstract "The dblp RDF schema is an ontology that models the semantic contents of the dblp computer science bibliography."@en ;
    dct:creator <https://dblp.org> ;
    dct:description "This ontology describes the RDF representation of the contents of the dblp computer science bibliography."@en ;
    dct:title "dblp RDF schema" ;
    a owl:Ontology ;
    owl:priorVersion <https://dblp.org/rdf/schema-2023-10-17> ;
    owl:versionIRI <https://dblp.org/rdf/schema-2024-06-14> ;
    owl:versionInfo "Fri 14 Jun 2024" .

dblp:AmbiguousCreator
    a rdfs:Class, owl:Class ;
    rdfs:comment "Not an actual creator, but an ambiguous proxy for an unknown number of unrelated actual creators of the same name. Associated publications do not have their true creators determined yet."@en ;
    rdfs:label "AmbiguousCreator"@en ;
    rdfs:subClassOf wd:Q48522, dblp:Creator .

dblp:Article
    a rdfs:Class, owl:Class ;
    rdfs:comment "A journal article."@en ;
    rdfs:label "Article"@en ;
    rdfs:subClassOf bibo:AcademicArticle, wd:Q13442814, dblp:Publication, schema:Article ;
    owl:equivalentClass dbo:Article .

dblp:AuthorSignature
    a rdfs:Class, owl:Class ;
    rdfs:comment "The information that links a publication to an author."@en ;
    rdfs:label "AuthorSignature"@en ;
    rdfs:subClassOf dblp:Signature .

dblp:Book
    a rdfs:Class, owl:Class ;
    rdfs:comment "A book or a thesis."@en ;
    rdfs:label "Book"@en ;
    rdfs:subClassOf dblp:Publication ;
    owl:equivalentClass dbo:Book, bibo:Book, wd:Q571, schema:Book .

dblp:Conference
    a rdfs:Class, owl:Class ;
    rdfs:comment "A conference or workshop series."@en ;
    rdfs:label "Conference"@en ;
    rdfs:subClassOf dblp:Stream ;
    owl:equivalentClass wd:Q47258130 .

dblp:Creator
    a rdfs:Class, owl:Class ;
    rdfs:comment "A creator of a publication."@en ;
    rdfs:label "Creator"@en ;
    rdfs:subClassOf dbo:Agent, bf:Agent, dct:Agent, wd:Q24229398, foaf:Agent, dblp:Entity .

dblp:Data
    a rdfs:Class, owl:Class ;
    rdfs:comment "Research data or artifacts."@en ;
    rdfs:label "Data"@en ;
    rdfs:subClassOf dblp:Publication ;
    owl:equivalentClass wd:Q17051824, schema:Dataset .

dblp:EditorSignature
    a rdfs:Class, owl:Class ;
    rdfs:comment "The information that links a publication to an editor."@en ;
    rdfs:label "EditorSignature"@en ;
    rdfs:subClassOf dblp:Signature .

dblp:Editorship
    a rdfs:Class, owl:Class ;
    rdfs:comment "An edited publication."@en ;
    rdfs:label "Editorship"@en ;
    rdfs:subClassOf dblp:Publication .

dblp:Entity
    a rdfs:Class, owl:Class ;
    rdfs:comment "An abstract, identifiable entity in dblp."@en ;
    rdfs:label "Entity"@en ;
    rdfs:subClassOf owl:Thing, wd:Q35120, schema:Thing .

dblp:Group
    a rdfs:Class, owl:Class ;
    rdfs:comment "A creator alias used by a group or consortium of persons."@en ;
    rdfs:label "Group"@en ;
    rdfs:subClassOf dblp:Creator ;
    owl:equivalentClass dbo:Organisation, bf:Organisation, wd:Q43229, foaf:Group, schema:Organization .

dblp:Incollection
    a rdfs:Class, owl:Class ;
    rdfs:comment "A part/chapter in a book or a collection."@en ;
    rdfs:label "Incollection"@en ;
    rdfs:subClassOf bibo:AcademicArticle, wd:Q13442814, dblp:Publication, schema:Chapter .

dblp:Informal
    a rdfs:Class, owl:Class ;
    rdfs:comment "An informal or other publication."@en ;
    rdfs:label "Informal"@en ;
    rdfs:subClassOf dblp:Publication ;
    owl:equivalentClass wd:Q1148359 .

dblp:Inproceedings
    a rdfs:Class, owl:Class ;
    rdfs:comment "A conference or workshop paper."@en ;
    rdfs:label "Inproceedings"@en ;
    rdfs:subClassOf bibo:AcademicArticle, wd:Q13442814, dblp:Publication, schema:Chapter .

dblp:Journal
    a rdfs:Class, owl:Class ;
    rdfs:comment "A periodically published journal."@en ;
    rdfs:label "Journal"@en ;
    rdfs:subClassOf dblp:Stream, schema:Periodical ;
    owl:equivalentClass wd:Q5633421 .

dblp:Person
    a rdfs:Class, owl:Class ;
    rdfs:comment "An actual person, who is a creator of a publication."@en ;
    rdfs:label "Person"@en ;
    rdfs:subClassOf dblp:Creator ;
    owl:equivalentClass dbo:Person, bf:Person, wd:Q5, foaf:Person, schema:Person .

dblp:Publication
    a rdfs:Class, owl:Class ;
    rdfs:comment "A publication."@en ;
    rdfs:label "Publication"@en ;
    rdfs:subClassOf dbo:WrittenWork, bf:Work, dct:BibliographicResource, bibo:Document, foaf:Document, dblp:Entity, schema:CreativeWork ;
    owl:equivalentClass wd:Q591041 .

dblp:Reference
    a rdfs:Class, owl:Class ;
    rdfs:comment "A reference work entry."@en ;
    rdfs:label "Reference"@en ;
    rdfs:subClassOf dblp:Publication ;
    owl:equivalentClass bibo:ReferenceSource, wd:Q10389811 .

dblp:Repository
    a rdfs:Class, owl:Class ;
    rdfs:comment "A source of data and/or artifact publications."@en ;
    rdfs:label "Repository"@en ;
    rdfs:subClassOf dblp:Stream ;
    owl:equivalentClass wd:Q5227240 .

dblp:Series
    a rdfs:Class, owl:Class ;
    rdfs:comment "A published series of volumes."@en ;
    rdfs:label "Series"@en ;
    rdfs:subClassOf dblp:Stream ;
    owl:equivalentClass wd:Q2217301 .

dblp:Signature
    a rdfs:Class, owl:Class ;
    rdfs:comment "The information that links a publication to a creator."@en ;
    rdfs:label "Signature"@en .

dblp:Stream
    a rdfs:Class, owl:Class ;
    rdfs:comment "A publication stream, i.e., a venue or source for publications."@en ;
    rdfs:label "Stream"@en ;
    rdfs:subClassOf dblp:Entity, schema:CreativeWorkSeries .

dblp:VersionRelation
    a rdfs:Class, owl:Class ;
    rdfs:comment "The information that links an (instanced) publication version to its general (concept) publication."@en ;
    rdfs:label "VersionRelation"@en .

dblp:Withdrawn
    a rdfs:Class, owl:Class ;
    rdfs:comment "A withdrawn publication item."@en ;
    rdfs:label "Withdrawn"@en ;
    rdfs:subClassOf dblp:Publication ;
    owl:equivalentClass wd:Q45182324 .

dblp:affiliation
    a rdf:Property ;
    rdfs:comment "A (past or present) affiliation of the creator. (Remark: This property currently just gives literal xsd:string values until institutions are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "affiliation"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dblp:creatorNote ;
    owl:equivalentProperty dbo:affiliation, wd:P1416, schema:affiliation .

dblp:archivedWebpage
    a rdf:Property ;
    rdfs:comment "The URL of an archived web page about this item, which may no longer be available in the web."@en ;
    rdfs:domain dblp:Entity ;
    rdfs:label "archivedWebpage"@en ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf dblp:webpage .

dblp:authorOf
    a rdf:Property ;
    rdfs:comment "The creator is the author of the publication."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "authorOf"@en ;
    rdfs:range dblp:Publication ;
    rdfs:subPropertyOf dblp:creatorOf ;
    owl:inverseOf dblp:authoredBy .

dblp:authoredBy
    a rdf:Property ;
    rdfs:comment "The publication is authored by the creator."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "authoredBy"@en ;
    rdfs:range dblp:Creator ;
    rdfs:subPropertyOf dblp:createdBy ;
    owl:equivalentProperty dbo:author, locrel:aut, wd:P50, schema:author ;
    owl:inverseOf dblp:authorOf .

dblp:awardWebpage
    a rdf:Property ;
    rdfs:comment "The URL of a web page about an award received by this creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "awardwebpage"@en ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf dblp:webpage .

dblp:bibtexType
    a rdf:Property ;
    rdfs:comment "The bibtex type of the publication, e.g. book, inproceedings, etc."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "bibtexType"@en ;
    rdfs:range bibtex:Entry .

dblp:coAuthorWith
    a rdf:Property, owl:SymmetricProperty ;
    rdfs:comment "The creator is co-author with the other creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "coAuthorWith"@en ;
    rdfs:range dblp:Creator ;
    rdfs:subPropertyOf dblp:coCreatorWith .

dblp:coCreatorWith
    a rdf:Property, owl:SymmetricProperty ;
    rdfs:comment "The creator is co-creator with the other creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "coCreatorWith"@en ;
    rdfs:range dblp:Creator ;
    rdfs:subPropertyOf foaf:knows .

dblp:coEditorWith
    a rdf:Property, owl:SymmetricProperty ;
    rdfs:comment "The creator is co-editor with the other creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "coEditorWith"@en ;
    rdfs:range dblp:Creator ;
    rdfs:subPropertyOf dblp:coCreatorWith .

dblp:createdBy
    a rdf:Property ;
    rdfs:comment "The publication is created by the creator."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "createdBy"@en ;
    rdfs:range dblp:Creator ;
    rdfs:subPropertyOf dc:creator, foaf:maker ;
    owl:equivalentProperty locrel:cre, dct:creator, wd:P170, schema:creator ;
    owl:inverseOf dblp:creatorOf .

dblp:creatorName
    a rdf:Property ;
    rdfs:comment "The full name of the creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "creatorname"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf wd:P2561, foaf:name, schema:name .

dblp:creatorNote
    a rdf:Property ;
    rdfs:comment "An additional note about the creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "creatorNote"@en ;
    rdfs:range xsd:string .

dblp:creatorOf
    a rdf:Property ;
    rdfs:comment "The creator of the publication."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "creatorOf"@en ;
    rdfs:range dblp:Publication ;
    rdfs:subPropertyOf foaf:made ;
    owl:inverseOf dblp:createdBy .

dblp:documentPage
    a rdf:Property ;
    rdfs:comment "The URL of the electronic edition of the publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "documentPage"@en ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf dblp:webpage ;
    owl:equivalentProperty bf:electronicLocator, bibo:uri .

dblp:doi
    a rdf:Property ;
    rdfs:comment "A Digital Object Identifier."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "doi"@en ;
    rdfs:range xsd:anyUri ;
    rdfs:subPropertyOf dblp:identifier ;
    owl:equivalentProperty locid:doi, datacite:doi .

dblp:editedBy
    a rdf:Property ;
    rdfs:comment "The publication is edited by the creator."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "editedBy"@en ;
    rdfs:range dblp:Creator ;
    rdfs:subPropertyOf dblp:createdBy ;
    owl:equivalentProperty dbo:editor, locrel:edt, bibo:editor, wd:P98, schema:editor ;
    owl:inverseOf dblp:editorOf .

dblp:editorOf
    a rdf:Property ;
    rdfs:comment "The creator is the editor of the publication."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "editorOf"@en ;
    rdfs:range dblp:Publication ;
    rdfs:subPropertyOf dblp:creatorOf ;
    owl:inverseOf dblp:editedBy .

dblp:formerStreamTitle
    a rdf:Property ;
    rdfs:comment "A former title of the stream."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "formerStreamTitle"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dblp:streamTitle .

dblp:hasSignature
    a rdf:Property ;
    rdfs:comment "A signature that links this publication to an creator."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "hasSignature"@en ;
    rdfs:range dblp:Signature ;
    owl:inverseOf dblp:signaturePublication .

dblp:hasVersion
    a rdf:Property ;
    rdfs:comment "The publication has a different, more specific (instance) publication as its version."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "hasVersion"@en ;
    rdfs:range dblp:VersionRelation ;
    owl:inverseOf dblp:versionConcept .

dblp:homepage
    a rdf:Property ;
    rdfs:comment "The URL of an academic homepage of this creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "homepage"@en ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf dblp:webpage ;
    owl:equivalentProperty wd:P856, foaf:homepage .

dblp:homonymousCreator
    a rdf:Property, owl:SymmetricProperty ;
    rdfs:comment "This creator shares a homonymous name with the other creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "homonymousCreator"@en ;
    rdfs:range dblp:Creator .

dblp:identifier
    a rdf:Property ;
    rdfs:comment "An abstract identifier."@en ;
    rdfs:domain dblp:Entity ;
    rdfs:label "identifier"@en ;
    rdfs:range xsd:anyUri ;
    owl:equivalentProperty locid:id .

dblp:indexPage
    a rdf:Property ;
    rdfs:comment "The URL of the dblp stream index page for this stream."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "indexPage"@en ;
    rdfs:range foaf:Document .

dblp:isVersion
    a rdf:Property ;
    rdfs:comment "The publication is a version of another, more general (concept) publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "isVersion"@en ;
    rdfs:range dblp:VersionRelation ;
    owl:inverseOf dblp:versionInstance .

dblp:isVersionOf
    a rdf:Property, owl:TransitiveProperty ;
    rdfs:comment "The publication is a version of another, more general (concept) publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "isVersionOf"@en ;
    rdfs:range dblp:Publication ;
    owl:equivalentProperty wd:P747 .

dblp:isbn
    a rdf:Property ;
    rdfs:comment "An International Standard Book Number."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "isbn"@en ;
    rdfs:range xsd:anyUri ;
    rdfs:subPropertyOf dblp:identifier ;
    owl:equivalentProperty locid:isbn, datacite:isbn .

dblp:iso4
    a rdf:Property ;
    rdfs:comment "The stream's ISO4 abbreviation."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "iso4"@en ;
    rdfs:range xsd:string ;
    owl:equivalentProperty wd:P1160 .

dblp:issn
    a rdf:Property ;
    rdfs:comment "An International Standard Serial Number."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "issn"@en ;
    rdfs:range xsd:anyUri ;
    rdfs:subPropertyOf dblp:identifier ;
    owl:equivalentProperty locid:issn, datacite:issn .

dblp:listedOnTocPage
    a rdf:Property ;
    rdfs:comment "The url of the dblp table of contents page listing this publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "listedOnTocPage"@en ;
    rdfs:range foaf:Document .

dblp:monthOfPublication
    a rdf:Property ;
    rdfs:comment "The month the publication has been published."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "monthOfPublication"@en ;
    rdfs:range xsd:gMonth ;
    rdfs:subPropertyOf wd:P2922 .

dblp:numberOfCreators
    a rdf:Property ;
    rdfs:comment "The number of creators who created this publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "numberOfCreators"@en ;
    rdfs:range xsd:integer .

dblp:omid
    a rdf:Property ;
    rdfs:comment "An OpenCitations Meta Identifier."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "omid"@en ;
    rdfs:range xsd:anyUri ;
    rdfs:subPropertyOf dblp:identifier ;
    owl:equivalentProperty datacite:omid .

dblp:orcid
    a rdf:Property ;
    rdfs:comment "An Open Researcher and Contributor ID."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "orcid"@en ;
    rdfs:range xsd:anyUri ;
    rdfs:subPropertyOf dblp:identifier ;
    owl:equivalentProperty locid:orcid, datacite:orcid .

dblp:pagination
    a rdf:Property ;
    rdfs:comment "The page numbers where the publication can be found."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "pagination"@en ;
    rdfs:range xsd:string ;
    owl:equivalentProperty bibo:pages, wd:P304, schema:pagination .

dblp:possibleActualCreator
    a rdf:Property ;
    rdfs:comment "This ambiguous creator may be (or may be not) just a disambiguation proxy for the other creator. Further actual creator candidates are possible."@en ;
    rdfs:domain dblp:AmbiguousCreator ;
    rdfs:label "possibleActualCreator"@en ;
    rdfs:range dblp:Creator ;
    rdfs:subPropertyOf dblp:homonymousCreator ;
    owl:inverseOf dblp:proxyAmbiguousCreator .

dblp:predecessorStream
    a rdf:Property ;
    rdfs:comment "This stream is a predecessor of the other stream."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "predecessorStream"@en ;
    rdfs:range dblp:Stream ;
    rdfs:subPropertyOf dblp:relatedStream ;
    owl:inverseOf dblp:successorStream .

dblp:primaryAffiliation
    a rdf:Property ;
    rdfs:comment "The primary affiliation of the creator. (Remark: This property currently just gives literal xsd:string values until institutions are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "primaryAffiliation"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dblp:affiliation .

dblp:primaryCreatorName
    a rdf:Property ;
    rdfs:comment "The primary full name of the creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "primaryCreatorName"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dbo:commonName, dblp:creatorName .

dblp:primaryDocumentPage
    a rdf:Property ;
    rdfs:comment "The primary URL of the electronic edition of the publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "primaryDocumentPage"@en ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf dblp:documentPage .

dblp:primaryHomepage
    a rdf:Property ;
    rdfs:comment "The primary URL of an academic homepage of this creator."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "primaryHomepage"@en ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf dblp:homepage .

dblp:primaryStreamTitle
    a rdf:Property ;
    rdfs:comment "The primary title of the stream."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "primaryStreamTitle"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dbo:commonName, dblp:streamTitle .

dblp:proxyAmbiguousCreator
    a rdf:Property ;
    rdfs:comment "This creator (and any of her fellow homonymous creators) is also represented by the given ambiguous creator in cases where the authorship of a publication is undetermined."@en ;
    rdfs:domain dblp:Creator ;
    rdfs:label "proxyAmbiguousCreator"@en ;
    rdfs:range dblp:AmbiguousCreator ;
    rdfs:subPropertyOf dblp:homonymousCreator ;
    owl:inverseOf dblp:possibleActualCreator .

dblp:publicationNote
    a rdf:Property ;
    rdfs:comment "An additional note to the publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publicationNote"@en ;
    rdfs:range xsd:string .

dblp:publishedAsPartOf
    a rdf:Property, owl:TransitiveProperty ;
    rdfs:comment "The publication has been published as a part of the other publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedAsPartOf"@en ;
    rdfs:range dblp:Publication ;
    rdfs:subPropertyOf wd:P1433, schema:isPartOf .

dblp:publishedBy
    a rdf:Property ;
    rdfs:comment "The publisher of the publication. (Remark: This property currently just gives literal xsd:string values until publishers are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedBy"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dc:publisher ;
    owl:equivalentProperty dct:publisher, wd:P123, schema:publisher .

dblp:publishedIn
    a rdf:Property ;
    rdfs:comment "The name of the series, the journal, or the book in which the publication has been published. (Remark: This property currently just gives literal xsd:string values until journals and conference series are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedIn"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf wd:P1433, schema:isPartOf .

dblp:publishedInBook
    a rdf:Property ;
    rdfs:comment "The name of the book in which the publication has been published. (Remark: This is currently an intermediate property that will be removed once journals and conference series are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedInBook"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dblp:publishedIn .

dblp:publishedInBookChapter
    a rdf:Property ;
    rdfs:comment "The chapter of the book in which the publication has been published. (Remark: This is currently an intermediate property that will be removed once journals and conference series are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedInBookChapter"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf wd:P792, schema:position ;
    owl:equivalentProperty bibo:chapter .

dblp:publishedInJournal
    a rdf:Property ;
    rdfs:comment "The name of the journal in which the publication has been published. (Remark: This is currently an intermediate property that will be removed once journals and conference series are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedInJournal"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dblp:publishedIn .

dblp:publishedInJournalVolume
    a rdf:Property ;
    rdfs:comment "The volume of the journal in which the publication has been published. (Remark: This is currently an intermediate property that will be removed once journals and conference series are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedInJournalVolume"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf wd:P478, schema:volumeNumber ;
    owl:equivalentProperty bibo:volume .

dblp:publishedInJournalVolumeIssue
    a rdf:Property ;
    rdfs:comment "The issue of the journal in which the publication has been published. (Remark: This is currently an intermediate property that will be removed once journals and conference series are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedInJournalIssue"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf wd:P433, schema:issueNumber ;
    owl:equivalentProperty bibo:issue .

dblp:publishedInSeries
    a rdf:Property ;
    rdfs:comment "The name of the series in which the publication has been published. (Remark: This is currently an intermediate property that will be removed once journals and conference series are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedInSeries"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dblp:publishedIn .

dblp:publishedInSeriesVolume
    a rdf:Property ;
    rdfs:comment "The volume of the series in which the publication has been published. (Remark: This is currently an intermediate property that will be removed once journals and conference series are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedInSeriesVolume"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf wd:P478, schema:volumeNumber ;
    owl:equivalentProperty bibo:volume .

dblp:publishedInStream
    a rdf:Property ;
    rdfs:comment "The conference series, the journal, or the repository in which the publication has been published."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishedInStream"@en ;
    rdfs:range dblp:Stream ;
    rdfs:subPropertyOf wd:P1433, schema:isPartOf .

dblp:publishersAddress
    a rdf:Property ;
    rdfs:comment "The address of the publisher. (Remark: This is currently an intermediate property that will be removed once publishers are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "publishersAddress"@en ;
    rdfs:range xsd:string .

dblp:relatedStream
    a rdf:Property, owl:SymmetricProperty ;
    rdfs:comment "This stream is related to the other stream in some unspecified way."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "relatedStream"@en ;
    rdfs:range dblp:Stream .

dblp:signatureCreator
    a rdf:Property ;
    rdfs:comment "A linked creator of the publication."@en ;
    rdfs:domain dblp:Signature ;
    rdfs:label "signatureCreator"@en ;
    rdfs:range dblp:Creator .

dblp:signatureDblpName
    a rdf:Property ;
    rdfs:comment "A dblp name (including any possible trailing homonym number) that links the publication to a creator."@en ;
    rdfs:domain dblp:Signature ;
    rdfs:label "signatureDblpName"@en ;
    rdfs:range xsd:string .

dblp:signatureOrcid
    a rdf:Property ;
    rdfs:comment "An ORCID that links the publication to a creator."@en ;
    rdfs:domain dblp:Signature ;
    rdfs:label "signatureOrcid"@en ;
    rdfs:range xsd:anyUri .

dblp:signatureOrdinal
    a rdf:Property ;
    rdfs:comment "The ordinal number of this signature for the publication, starting with 1."@en ;
    rdfs:domain dblp:Signature ;
    rdfs:label "signatureOrdinal"@en ;
    rdfs:range xsd:integer .

dblp:signaturePublication
    a rdf:Property ;
    rdfs:comment "The publication of this signature."@en ;
    rdfs:domain dblp:Signature ;
    rdfs:label "signaturePublication"@en ;
    rdfs:range dblp:Publication ;
    owl:inverseOf dblp:hasSignature .

dblp:streamTitle
    a rdf:Property ;
    rdfs:comment "A title of the stream."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "streamTitle"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf wd:P2561, foaf:name, schema:name .

dblp:subStream
    a rdf:Property ;
    rdfs:comment "This stream is (or was) a part of the other stream."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "subStream"@en ;
    rdfs:range dblp:Stream ;
    rdfs:subPropertyOf dblp:relatedStream ;
    owl:inverseOf dblp:superStream .

dblp:successorStream
    a rdf:Property ;
    rdfs:comment "This stream is a successor of the other stream."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "successorStream"@en ;
    rdfs:range dblp:Stream ;
    rdfs:subPropertyOf dblp:relatedStream ;
    owl:inverseOf dblp:predecessorStream .

dblp:superStream
    a rdf:Property ;
    rdfs:comment "This stream has (or had) the other stream as a part."@en ;
    rdfs:domain dblp:Stream ;
    rdfs:label "superStream"@en ;
    rdfs:range dblp:Stream ;
    rdfs:subPropertyOf dblp:relatedStream ;
    owl:inverseOf dblp:subStream .

dblp:thesisAcceptedBySchool
    a rdf:Property ;
    rdfs:comment "The school where the publication (typically a thesis) has been accepted. (Remark: This property currently just gives literal xsd:string values until institutions are modelled as proper entities.)"@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "thesisAcceptedBySchool"@en ;
    rdfs:range xsd:string .

dblp:title
    a rdf:Property ;
    rdfs:comment "The title of the publication."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "title"@en ;
    rdfs:range xsd:string ;
    rdfs:subPropertyOf dc:title, schema:name ;
    owl:equivalentProperty dct:title, wd:P1476 .

dblp:versionConcept
    a rdf:Property ;
    rdfs:comment "The linked general (concept) publication."@en ;
    rdfs:domain dblp:VersionRelation ;
    rdfs:label "versionConcept"@en ;
    rdfs:range dblp:Publication .

dblp:versionInstance
    a rdf:Property ;
    rdfs:comment "The linked specific (instance) publication version."@en ;
    rdfs:domain dblp:VersionRelation ;
    rdfs:label "versionInstance"@en ;
    rdfs:range dblp:Publication .

dblp:versionLabel
    a rdf:Property ;
    rdfs:comment "The human-readable version label of the specific (instance) publication version."@en ;
    rdfs:domain dblp:VersionRelation ;
    rdfs:label "versionLabel"@en ;
    rdfs:range xsd:string .

dblp:versionOrdinal
    a rdf:Property ;
    rdfs:comment "The ordinal number of the specific (instance) publication version. This number is solely intended for sorting purposes: bigger numbers indicate later versions. Version ordinals do not need to describe a complete number range, nor is there a necessary relationship to the version labels."@en ;
    rdfs:domain dblp:VersionRelation ;
    rdfs:label "versionOrdinal"@en ;
    rdfs:range xsd:integer .

dblp:versionUri
    a rdf:Property ;
    rdfs:comment "An (optional) URI of identifying the linked specific (instance) publication version."@en ;
    rdfs:domain dblp:VersionRelation ;
    rdfs:label "versionUri"@en ;
    rdfs:range xsd:anyUri .

dblp:webpage
    a rdf:Property ;
    rdfs:comment "The URL of a web page about this item."@en ;
    rdfs:domain dblp:Entity ;
    rdfs:label "webpage"@en ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf wd:P2699, schema:url ;
    owl:equivalentProperty foaf:page .

dblp:wikidata
    a rdf:Property ;
    rdfs:comment "A wikidata item."@en ;
    rdfs:domain dblp:Entity ;
    rdfs:label "wikidata"@en ;
    rdfs:range xsd:anyUri ;
    rdfs:subPropertyOf dblp:identifier ;
    owl:equivalentProperty locid:wikidata, datacite:wikidata .

dblp:wikipedia
    a rdf:Property ;
    rdfs:comment "The URL of an (English) Wikipedia article about this item."@en ;
    rdfs:domain dblp:Entity ;
    rdfs:label "wikipedia"@en ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf dblp:webpage .

dblp:yearOfEvent
    a rdf:Property ;
    rdfs:comment "The year the conference or workshop contribution has been presented."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "yearOfEvent"@en ;
    rdfs:range xsd:gYear .

dblp:yearOfPublication
    a rdf:Property ;
    rdfs:comment "The year the publication's issue or volume has been published."@en ;
    rdfs:domain dblp:Publication ;
    rdfs:label "yearOfPublication"@en ;
    rdfs:range xsd:gYear ;
    owl:equivalentProperty dbo:publicationDate, dct:issued, wd:P577, schema:publication .
"""

# Input properties to find domain and range for
input_properties = [
    "https://dblp.org/rdf/schema#authoredBy",
    "https://dblp.org/rdf/schema#publishedIn"
]

# Initialize an RDF graph
g = Graph()

# Parse the ontology schema (assuming it's in Turtle format)
g.parse(data=ontology_schema, format="ttl")

# Define namespaces
DBLP = Namespace("https://dblp.org/rdf/schema#")
XSD = Namespace("http://www.w3.org/2001/XMLSchema#")

# Dictionary to store the results
property_info = {}

# Function to get the subject (Domain) and object (Range) of a property
def get_domain_and_range(graph, prop_uri):
    """Fetches the domain and range for a given property URI from the graph."""
    prop = URIRef(prop_uri)
    
    # Get Domain (rdfs:domain)
    domains = list(graph.objects(prop, RDFS.domain))
    # Get Range (rdfs:range)
    ranges = list(graph.objects(prop, RDFS.range))
    
    # Simple logic: assume one domain and one range based on the DBLP schema structure
    domain = domains[0] if domains else None
    range_ = ranges[0] if ranges else None
    
    return domain, range_

# Process each input property
for prop_uri in input_properties:
    domain, range_ = get_domain_and_range(g, prop_uri)
    
    # Format the URIs to use the prefix 'dblp:' or 'xsd:' as in the output
    # This involves a simple string replacement based on the known namespaces
    def format_uri(uri):
        if not uri:
            return "None"
        uri_str = str(uri)
        if uri_str.startswith(str(DBLP)):
            return "dblp:" + uri_str.replace(str(DBLP), "")
        elif uri_str.startswith(str(XSD)):
            return "xsd:" + uri_str.replace(str(XSD), "")
        # Fallback for other namespaces if necessary, but DBLP properties in the prompt
        # only reference dblp: and xsd: types.
        return uri_str

    if domain and range_:
        formatted_domain = format_uri(domain)
        formatted_range = format_uri(range_)
        formatted_property = format_uri(URIRef(prop_uri))
        property_info[prop_uri] = f"<{formatted_domain}, {formatted_property}, {formatted_range}>"
    else:
        property_info[prop_uri] = f"<{format_uri(domain)}, {format_uri(URIRef(prop_uri))}, {format_uri(range_)}>"


# Generate the final output string in the specified format
output_list = [
    property_info.get("https://dblp.org/rdf/schema#authoredBy"),
    property_info.get("https://dblp.org/rdf/schema#publishedIn")
]
final_output = " ".join(output_list)

print(final_output)

<dblp:Publication, dblp:authoredBy, dblp:Creator> <dblp:Publication, dblp:publishedIn, xsd:string>

In [2]:
from rdflib import Graph, URIRef, RDFS, Namespace
import os

# Define the input properties
input_properties = [
    "https://dblp.org/rdf/schema#authoredBy",
    "https://dblp.org/rdf/schema#publishedIn"
]

# Define the file path for the ontology schema
ONTOLOGY_FILE_PATH = "/Users/sherrypan/GitHub/GAR_SKGQA/datasets/dblp/project_data/dblp_schema.ttl"

# Define namespaces for output formatting
DBLP = Namespace("https://dblp.org/rdf/schema#")
XSD = Namespace("http://www.w3.org/2001/XMLSchema#")

def format_uri(uri):
    """Formats a full URI to its prefixed name (QName) or returns the string if not recognized."""
    if not uri:
        return "None"
    uri_str = str(uri)
    if uri_str.startswith(str(DBLP)):
        return "dblp:" + uri_str.replace(str(DBLP), "")
    elif uri_str.startswith(str(XSD)):
        return "xsd:" + uri_str.replace(str(XSD), "")
    return uri_str

def get_property_signature_from_file(file_path, properties):
    """
    Loads the ontology from a local file and extracts the (Domain, Property, Range) 
    signature for the given list of properties.
    """
    if not os.path.exists(file_path):
        return f"Error: File not found at {file_path}"
        
    g = Graph()
    
    try:
        # Load the graph directly from the Turtle file path
        print(f"Reading ontology from: {file_path}")
        g.parse(file_path, format="ttl")
    except Exception as e:
        return f"Error parsing ontology file: {e}"
    
    output_signatures = []

    for prop_uri in properties:
        prop = URIRef(prop_uri)
        
        # Query for rdfs:domain and rdfs:range
        # Assuming only one value for domain and range for simplicity of this task
        domains = list(g.objects(prop, RDFS.domain))
        ranges = list(g.objects(prop, RDFS.range))
        
        domain = domains[0] if domains else None
        range_ = ranges[0] if ranges else None
        
        formatted_domain = format_uri(domain)
        formatted_property = format_uri(prop)
        formatted_range = format_uri(range_)
        
        output_signatures.append(f"<{formatted_domain}, {formatted_property}, {formatted_range}>")
    
    return " ".join(output_signatures)

# Execute the function using the file path
result = get_property_signature_from_file(ONTOLOGY_FILE_PATH, input_properties)
print(result)

Reading ontology from: /Users/sherrypan/GitHub/GAR_SKGQA/datasets/dblp/project_data/dblp_schema.ttl
<dblp:Publication, dblp:authoredBy, dblp:Creator> <dblp:Publication, dblp:publishedIn, xsd:string>

In [5]:
import requests
from urllib.parse import quote_plus
from typing import List, Dict

# --- Configuration ---
# SPARQL_ENDPOINT = "https://sparql.dblp.org/sparql"
SPARQL_ENDPOINT = "http://localhost:7021"
INPUT_ENTITIES = [
    "<https://dblp.org/pid/82/9897>",
    "<https://dblp.org/pid/66/4077>"
]

# SPARQL query template (using format strings for insertion)
SPARQL_TEMPLATE = """
SELECT ?type
WHERE {{
  {entity_uri} <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
}}
"""

# Define namespaces for abbreviation in output
DBLP_SCHEMA_NS = "https://dblp.org/rdf/schema#"

def format_uri(uri_str: str, namespace: str) -> str:
    """Abbreviates a full URI string using a provided namespace prefix (e.g., dblp:)."""
    if uri_str.startswith(namespace):
        return "dblp:" + uri_str[len(namespace):]
    return uri_str

def fetch_entity_types(endpoint: str, entities: List[str]) -> Dict[str, str]:
    """
    Executes SPARQL queries for a list of entities to find their RDF type.
    
    Args:
        endpoint: The SPARQL endpoint URL.
        entities: A list of entity URIs (as strings) to query.
        
    Returns:
        A dictionary mapping the original entity URI to its abbreviated type.
    """
    results_map = {}
    
    for entity_uri in entities:
        # 1. Format the SPARQL query
        # Remove the < > wrappers for interpolation into the query, but ensure the entity is still treated as a URI
        # The entity_uri variable already includes < and > as per the input format.
        query = SPARQL_TEMPLATE.format(entity_uri=entity_uri)
        
        # 2. Encode the query for the URL
        params = {'query': query, 'format': 'json'}
        
        # 3. Send the HTTP GET request
        try:
            response = requests.get(endpoint, params=params, timeout=10)
            response.raise_for_status() # Raise an exception for bad status codes (4xx or 5xx)
            data = response.json()

            # 4. Process the results
            types = data.get('results', {}).get('bindings', [])
            
            if types:
                # The query returns the type URI. We take the first one found.
                type_uri = types[0]['type']['value']
                
                # Format the entity URI for output (removing < >)
                clean_entity_uri = entity_uri.strip('<>')
                
                # Format the type URI (e.g., to dblp:Person)
                abbreviated_type = format_uri(type_uri, DBLP_SCHEMA_NS)
                
                results_map[clean_entity_uri] = abbreviated_type
            else:
                clean_entity_uri = entity_uri.strip('<>')
                results_map[clean_entity_uri] = "Unknown Type"

        except requests.exceptions.RequestException as e:
            print(f"Error querying {entity_uri}: {e}")
            results_map[entity_uri.strip('<>')] = "Query Failed"
            
    return results_map

def format_output(results: Dict[str, str]) -> str:
    """Formats the results dictionary into the requested string format."""
    output_parts = [f"<{entity}> : {entity_type}" for entity, entity_type in results.items()]
    return " ".join(output_parts)

# --- Execution ---
entity_types = fetch_entity_types(SPARQL_ENDPOINT, INPUT_ENTITIES)
final_output = format_output(entity_types)

print(final_output)

<https://dblp.org/pid/82/9897> : dblp:Creator <https://dblp.org/pid/66/4077> : dblp:Creator

In [6]:
a = "<https://dblp.org/rdf/schema#publishedIn>"

In [9]:
b = a.split("#")[-1].strip(">")

In [14]:
c = "dblp:" + b
print(c)  # Output: dblp:publishedIn

dblp:publishedIn

In [16]:
# read a csv file with three columns: property, domain and range
import pandas as pd

df = pd.read_csv("/Users/sherrypan/GitHub/GAR_SKGQA/datasets/dblp/project_data/dblp_property_schema.csv")
# given a list of properties, output their domain and range in the format <domain, property, range>
input_properties = [
    "https://dblp.org/rdf/schema#authoredBy",
    "https://dblp.org/rdf/schema#publishedIn"
]
output_list = []
for prop in input_properties:
    prop_name = "dblp:" + prop.split("#")[-1].strip(">")
    row = df[df['property'] == prop_name]
    if not row.empty:
        domain = row['domain'].values[0]
        range_ = row['range'].values[0]
        output_list.append(f"<{domain}, {prop_name}, {range_}>")

In [17]:
output_list

['<dblp:Publication, dblp:authoredBy, dblp:Creator>',
 '<dblp:Publication, dblp:publishedIn, xsd:string>']

In [22]:

entities = str("<https://dblp.org/pid/229/5178>, <https://dblp.org/pid/73/8951>").split(", ")
endpoint_url = "http://localhost:7021/sparql"
from SPARQLWrapper import SPARQLWrapper, JSON, POST
SPARQL_TEMPLATE = """
    SELECT ?type
    WHERE {{
    {entity_uri} <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
    }}
    """
entity_types_list = []
for entity_uri in entities:
    query = SPARQL_TEMPLATE.format(entity_uri=entity_uri)
    wrapper = SPARQLWrapper(endpoint_url)
    wrapper.setMethod(POST)
    wrapper.setReturnFormat(JSON)
    wrapper.setQuery(query)

    results = wrapper.query().convert()
    types = [result["type"]["value"] for result in results["results"]["bindings"]]
    # Format the output
    # Abbreviate the type URIs to use the 'dblp:' prefix where applicable
    abbreviated_types = []
    for t in types:
        if t.startswith("https://dblp.org/rdf/schema#"):
            abbreviated_types.append("dblp:" + t.split("#")[-1])
        else:
            abbreviated_types.append(t)
    types = abbreviated_types
    entity_types = f"{entity_uri}: " + ", ".join(types)
    entity_types_list.append(entity_types)
final_output = " \n".join(entity_types_list)
print(final_output)

<https://dblp.org/pid/229/5178>: dblp:Creator, dblp:Person
<https://dblp.org/pid/73/8951>: dblp:Creator, dblp:Person

In [24]:
file = "/Users/sherrypan/GitHub/GAR_SKGQA/results/dblp/zero_triple_questions.csv"

zero_triple_list = []
df = pd.read_csv(file)
for _, row in df.iterrows():
    if row['triples'] == 0:
        zero_triple_list.append(row['id'])

In [30]:
# read a csv with question id
file = "/Users/sherrypan/GitHub/GAR_SKGQA/results/dblp/non_zero_ids.csv"
non_zero_ids = []
df = pd.read_csv(file)
for _, row in df.iterrows():
    non_zero_ids.append(row['id'])
zero_triple_list = []
for i in range(1, 2001):
    id_str = f"Q{i:04d}"
    if id_str not in non_zero_ids:
        zero_triple_list.append(id_str)
print(zero_triple_list)  # Output the list of question ids with zero triples
# save the list to a csv file
output_file = "/Users/sherrypan/GitHub/GAR_SKGQA/results/dblp/zero_triple_questions.csv"
df = pd.DataFrame(zero_triple_list, columns=['id'])
df.to_csv(output_file, index=False)

['Q0319', 'Q0464', 'Q0565', 'Q0591', 'Q0607', 'Q0614', 'Q0617', 'Q0621', 'Q0634', 'Q0649', 'Q0653', 'Q0655', 'Q0658', 'Q0667', 'Q0674', 'Q0687', 'Q0703', 'Q0764', 'Q0814', 'Q0830', 'Q0961', 'Q0984', 'Q1103', 'Q1111', 'Q1159', 'Q1226', 'Q1264', 'Q1266', 'Q1297', 'Q1301', 'Q1302', 'Q1303', 'Q1305', 'Q1310', 'Q1315', 'Q1316', 'Q1319', 'Q1322', 'Q1326', 'Q1331', 'Q1334', 'Q1335', 'Q1336', 'Q1337', 'Q1338', 'Q1340', 'Q1341', 'Q1343', 'Q1345', 'Q1347', 'Q1350', 'Q1351', 'Q1352', 'Q1353', 'Q1355', 'Q1358', 'Q1362', 'Q1365', 'Q1367', 'Q1372', 'Q1376', 'Q1381', 'Q1384', 'Q1387', 'Q1388', 'Q1390', 'Q1391', 'Q1393', 'Q1394', 'Q1395', 'Q1396', 'Q1397', 'Q1398', 'Q1400', 'Q1406', 'Q1415', 'Q1416', 'Q1421', 'Q1445', 'Q1454', 'Q1456', 'Q1458', 'Q1488', 'Q1489', 'Q1505', 'Q1516', 'Q1521', 'Q1525', 'Q1533', 'Q1534', 'Q1541', 'Q1548', 'Q1549', 'Q1550', 'Q1555', 'Q1558', 'Q1562', 'Q1574', 'Q1590', 'Q1595', 'Q1772', 'Q1780', 'Q1781', 'Q1782', 'Q1787', 'Q1788', 'Q1789', 'Q1794', 'Q1795', 'Q1797', 'Q1802', 'Q1803', 'Q1804', 'Q1806', 'Q1807', 'Q1808', 'Q1809', 'Q1810', 'Q1811', 'Q1813', 'Q1814', 'Q1815', 'Q1816', 'Q1817', 'Q1818', 'Q1819', 'Q1821', 'Q1823', 'Q1824', 'Q1825', 'Q1827', 'Q1830', 'Q1833', 'Q1835', 'Q1836', 'Q1837', 'Q1838', 'Q1839', 'Q1840', 'Q1841', 'Q1842', 'Q1843', 'Q1844', 'Q1845', 'Q1846', 'Q1847', 'Q1848', 'Q1849', 'Q1850', 'Q1851', 'Q1853', 'Q1854', 'Q1855', 'Q1858', 'Q1859', 'Q1861', 'Q1863', 'Q1864', 'Q1866', 'Q1867', 'Q1868', 'Q1869', 'Q1871', 'Q1872', 'Q1873', 'Q1874', 'Q1875', 'Q1877', 'Q1878', 'Q1885', 'Q1886', 'Q1887', 'Q1888', 'Q1891', 'Q1892', 'Q1894', 'Q1895', 'Q1896', 'Q1899', 'Q1900', 'Q1901', 'Q1902', 'Q1903', 'Q1904', 'Q1905', 'Q1909', 'Q1910', 'Q1911', 'Q1912', 'Q1913', 'Q1914', 'Q1915', 'Q1916', 'Q1919', 'Q1920', 'Q1921', 'Q1922', 'Q1925', 'Q1928', 'Q1929', 'Q1930', 'Q1931', 'Q1932', 'Q1933', 'Q1934', 'Q1935', 'Q1936', 'Q1938', 'Q1939', 'Q1940', 'Q1941', 'Q1942', 'Q1946', 'Q1949', 'Q1950', 'Q1952', 'Q1954', 'Q1956', 'Q1957', 'Q1959', 'Q1960', 'Q1961', 'Q1962', 'Q1963', 'Q1965', 'Q1966', 'Q1969', 'Q1971', 'Q1972', 'Q1973', 'Q1974', 'Q1975', 'Q1976', 'Q1979', 'Q1980', 'Q1981', 'Q1982', 'Q1985', 'Q1986', 'Q1987', 'Q1990', 'Q1992', 'Q1995', 'Q1996', 'Q1997', 'Q1998', 'Q2000']

In [46]:
query = """
PREFIX dblp: <https://dblp.org/rdf/schema#>
select *
WHERE {
<https://dblp.org/rec/conf/acl/CirikMB22> dblp:authoredBy ?author .
}
limit 1
"""
wrapper = SPARQLWrapper("https://sparql.dblp.org/sparql")
# local dblp SPARQL endpoint: http://localhost:7020
wrapper.setMethod(POST)
wrapper.setReturnFormat(JSON)
wrapper.setQuery(query)
results = wrapper.query().convert()
print(results)

{'head': {'vars': ['author']}, 'results': {'bindings': [{'author': {'type': 'uri', 'value': 'https://dblp.org/pid/136/8682'}}]}}